### ISSUE TITLE
User education to not use prefix in API client

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#1014]
- Since we don't have support for prefix's in the API client, users should be made aware to use the numerical portion and not with the prefix. using the prefix in the API client will throw an error.
- i.e. use 12345, and not DS-12345

**Comment by dgmccart** [comment]
This was added to the data organization page. For example, "Dataset IDs start with DS (e.g. DS-10000; note that only the numeric part is supported in the API)." In the API reference, the type is specified as numeric for each of those IDs.
