### ISSUE TITLE
Data does not exist on server (dataset ID 10021)

### ISSUE THREAD

**Issue by shahpnmlab** [chanzuckerberg/cryoet-data-portal#1029]
hi,
I am trying to download tomograms for dataset ID `10021` at a voxel spacing of  8.832Å/px. However this data does not appear to be on the server.  
Executing -
`aws s3 --no-sign-request cp s3://cryoet-data-portal-public/10021/lma2019-08-21-1/Tomograms/VoxelSpacing8.832/CanonicalTomogram/lma2019-08-21-1.mrc lma2019-08-21-1.mrc`
results in -
`fatal error: An error occurred (404) when calling the HeadObject operation: Key "10021/lma2019-08-21-1/Tomograms/VoxelSpacing8.832/CanonicalTomogram/lma2019-08-21-1.mrc" does not exist`

Best,
Pranav

**Comment by shahpnmlab** [comment]
Actually it does exist but has the wrong pixel size encoded in the header. Datasets sampled at 8.00Apx and 8.832Apx have the same pixel dimensions. When the pixel size is corrected, the point cloud for identifed macromolecular assemblies (shared privately) matches the tomogram precisely.

**Comment by daniel-ji** [comment]
Hi @shahpnmlab, 

Sorry for the inconvenience. Yes, you are correct that it does not exist on the server. We'll be syncing the data from a staging bucket in the next few days, if that's alright. How urgently do you need this mrc file?

**Comment by shahpnmlab** [comment]
No worries @daniel-ji, I have managed to make it work for my particular application with the data sampled at 8Å/px so not very urgent. I do want to point out that the pixel dimensions of the tomograms sampled at 8 and 8.832 are incorrect in so far as neither can be the same, the 8Å/px dims should be 1.104 times larger than the tomos sampled at 8.832Å/px (unless changes have been made to unit cell parameters in the image header).

**Comment by daniel-ji** [comment]
Noted, thank you!

**Comment by manasaV3** [comment]
Hey @shahpnmlab 
Thank you very much for reporting this. 

Sorry about the inconvenience. There is supposed to be exactly one voxel spacing for this dataset's run at this point of time and it is 8.832Å.  

There were some issues with the initial data resulting in the voxel spacing specifications being specified as 8Å/px incorrectly. But, the patch to update to the correct voxel spacings didn't migrate all the relevant resources correctly. So, we were incorrectly seeing two voxel spacings for the same tomogram data. We have update the portal to reflect the correct voxel spacing. 

Please let us know, if this doesn't address your issue.

**Comment by junxini** [comment]
Hi @shahpnmlab, we'll move forward with closing this ticket as this bug has been addressed. Feel free to re-open if there are pending questions/concerns. Thanks again for logging this bug!
