### ISSUE TITLE
Update oriented point rendering in neuroglancer

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#1059]
## Motivation
At present, Neuroglancer renders oriented points in the same manner as simple points, without incorporating the rotation vector component into the visualization. This potentially results in users only getting partial information from the visualization. This can be improved by adding the direction vector to the visualization. 

The metacell team has updated the cryoet's neuroglancer repository with components for rending the orientation. This can be used for updating the existing visualization components. 

## Definition of Done
The oriented points are rendered in neuroglancer with rotational vectors.

### 1. Integrate the new the precompute method for oriented point
The visualization precompute importer (ref: [here](https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/main/ingestion_tools/scripts/importers/visualization_precompute.py#L91)) needs to be updated with changes (if required) to incorporate the oriented points visualization.

The method for generating the precompute (ref: [here](https://github.com/chanzuckerberg/cryoet-data-portal-neuroglancer/blob/main/cryoet_data_portal_neuroglancer/precompute/points.py#L125)) maintains the existing signature, with an additional parameter of a default value. The integration needs to sanity check that the precomputation creates valid output objects of sharded precomputed data that can be rendered by neuroglancer.

### 2. Update the config layer generation
The visualization config importer (ref: [here](https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/main/ingestion_tools/scripts/importers/visualization_config.py)) needs to be updated with if required for the oriented points visualizations.

The method for generating the oriented point layer in neuroglancer (ref: [here](https://github.com/chanzuckerberg/cryoet-data-portal-neuroglancer/blob/main/cryoet_data_portal_neuroglancer/models/json_generator.py#L170)) should be integrated and validated to ensure it generates config that reflects the newer visualization

### 3. Regenerate the related components 
Regenerate the annotation precomputes and neuroglancer config generations for all runs that have oriented point annotations.

### 4. Update Production

Sync data to production bucket after validating the data in staging, and update the neuroglancer field in tomogram table for datasets with oriented point annotaions.

## Related PRs

https://github.com/chanzuckerberg/cryoet-data-portal-neuroglancer/pull/13

**Comment by junxini** [comment]
@manasaV3 + @Bento007 to help with pointing

**Comment by manasaV3** [comment]
Related https://github.com/chanzuckerberg/cryoet-data-portal-neuroglancer/issues/18

**Comment by manasaV3** [comment]
@Bento007 Let me know if more information is needed for pointing this. :)

**Comment by junxini** [comment]
this ticket will be to double check Metacell's solution recommendation

**Comment by manasaV3** [comment]
This issue should fix the bug raised in: https://github.com/chanzuckerberg/cryoet-data-portal-neuroglancer/issues/18
