### ISSUE TITLE
Feature: Add "simulated" as a valid method type for annotations. 

### ISSUE THREAD

**Issue by uermel** [chanzuckerberg/cryoet-data-portal#1076]
None of the three method types currently present ("automated", "manual" or "hybrid") are fully appropriate for the case of simulated data. We currently have 1 new simulated dataset from CZII and there will be additional simulated data in the future. 

> Automated: Annotations were generated using automated tools or algorithms **without supervision**.

Simulated data is usually created with strong supervision (i.e. it is exactly known where which species is located). "Automated" annotations can also not be ground truth as per the validation rules.

> Hybrid: Annotations were generated using a combination of automated and **manual methods**.

Simulated data does not usually involve manual post-processing. 

> Manual: Annotations were created by hand.

As above. 

In order to correctly label the method type for simulated data I would suggest: 

* Add method type: simulated
* Update API docs and portal documentation
* Validation: simulated annotations can be ground truth.
* Add tooltip: 
   Simulated: Annotations were generated by simulation tools or algorithms.

**Comment by manasaV3** [comment]
The support for this field has been added by @daniel-ji 's work. 
https://github.com/chanzuckerberg/cryoet-data-portal-backend/pull/370 introduces the simulated method type for annotations.
