### ISSUE TITLE
Object ID instead of GO ID filter in Runs page

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#1082]
**Describe the bug**
GO ID filter seems to be changed to Object ID in Runs page

**To Reproduce**
1. Go to https://cryoetdataportal.czscience.com/runs/8273?object=membrane
2. Pay attention to filter panel

**Screenshots**
<img width="975" alt="Screenshot 2024-08-28 at 2 24 21 PM" src="https://github.com/user-attachments/assets/650e531a-dff1-4ce8-bccf-909f6765d86e">

**Comment by uermel** [comment]
This is an intentional change, as the object ID could now also be a UniProtKB accession code. For that reason, a more general term was chosen for that filter. This also reflects the name of the field in the backend.

**Comment by junxini** [comment]
FYI @Janeece @kev-zunshiwang on filter name change

**Comment by junxini** [comment]
closing as this was intentional

**Comment by Janeece** [comment]
logged change in masterfile update ticket #1167
