### ISSUE TITLE
Single Run Page - Annotation Metadata 

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#111]
User story: (4.2) I want to see all the annotation metadata from single run page, so that I can access detailed information

Tasks

- [ ] full list of annotation metadata accessible but initially tucked away (likely via panel) - open via "more info" within each row within the table 
- [ ] when panel is open, the rest of the page (outside of the panel) is greyed out and not accessible - user to click on "X" or somewhere outside of the panel to close
- [ ]  the annotation row that metadata is opened from is highlighted in gray

Link to design: https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=1310%3A11321&mode=dev

**Comment by Janeece** [comment]
Screenshot from Design:


![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/714389b6-42c4-4c55-a57b-fb0a029985ae)

**Comment by lauramarcos** [comment]
Following bug was found during testing:

Page not greyed out and accesible when right panel is opened [#245](https://github.com/chanzuckerberg/cryoet-data-portal/issues/245)
