### ISSUE TITLE
Update link locations on Portal UI

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#1111]
The Portal UI has many links that point to the FAQ page, but the user must find the relevant question in the list of FAQ questions since we do not have a method to open the FAQ accordions from a link. We have added content to the docsite to address this FAQ questions, and we'd like to point the relevant anchors on docsite pages instead of to the Portal FAQ.

An audit of the Portal links was [completed here](https://docs.google.com/spreadsheets/d/1QEPiDcjGJYWSZXsbRjwHd9aeZjbk_tvv2UQ4DKyMwxk/edit?gid=1603036675#gid=1603036675), which details the current and the desired link locations. Many links can be updated by making a PR on [this file](https://github.com/chanzuckerberg/cryoet-data-portal/blob/427c97db0741a52bfdec572a446b1e346b4c95c9/frontend/packages/data-portal/public/locales/en/translation.json#L298).

**Comment by junxini** [comment]
@dgmccart @melissawm - i'm in the process of cleaning up some tickets and wanted to check if this ticket status is accurate

**Comment by melissawm** [comment]
I believe this is solved.

**Comment by junxini** [comment]
thanks Melissa for confirming. @dgmccart i'll mark this as completed, but feel free to reopen if that's not accurate.
