### ISSUE TITLE
Update ML Challenge Page Copy

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#1156]
The current ML Challenge page has placeholders for additional content. we are anticipating 2 copy updates:

Update 1: update the content pre launch, whenever copy is ready <-- **this ticket is for update 1**
* link to designs: https://www.figma.com/design/aL3EkC3uM17oFDmTC5h4S8/Janeece%2F-Kevin---ML-Challenge-Page?node-id=762-3331&m=dev

Update 2: separate ticket in Q4 -- update copy to be pushed to production on the day of ML Challenge Launch

**Comment by junxini** [comment]
Copy and design not yet finalized. @kne42 i will comment on this ticket when it's ready

**Comment by junxini** [comment]
@kne42 this ticket is ready! i've updated the design link in the ticket with what Janeece shared

**Comment by junxini** [comment]
need to block this for now per Kaggle's request @kne42

**Comment by junxini** [comment]
Work was completed but was not released due to Kaggle's request
