### ISSUE TITLE
Tilt range filter is not working as expected and Clear filters message is not displayed in Dataset page

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#1182]
**Describe the bug**
Tilt range is not bringing up any data

**To Reproduce**
1. Go to (https://frontend.cryoet.staging.si.czi.technology/datasets/10301?ground_truth=true)
2. Click on Tilt Range filter and enter (-52.01° to 49.99°) This tilt range is from https://frontend.cryoet.staging.si.czi.technology/runs/13867?ground_truth=true

**Expected Results**
1. Run corresponding to entered tilt range should be listed in applet
2. If no results found, where is the "Clear filters" message?

**Screenshots**

https://github.com/user-attachments/assets/4498d78a-0e85-4992-bfb5-4f365f9a246a

**Comment by junxini** [comment]
good find Laura! 

this is for reference for anyone who picks up this ticket - the "clear filters" message is the error state, such as this:

![Image](https://github.com/user-attachments/assets/3f6cddcc-2b15-430e-90a5-9c7c28d45f13)

**Comment by junxini** [comment]
this has been fixed
