### ISSUE TITLE
Download tomogram only

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#120]
User story: (5.5) I want to download specific tomograms and/or annotations so that I have targeted data without unnecessarily using up memory

Tasks
_if user select "Download Tomogram Only"_
- [ ] dialog box renders to ask user to input tomogram sampling and tomogram processing
  - tomogram sampling defaults to smallest sampling size
  - processing defaults to whichever is considered canonical tomogram
- [ ] once user selects "next", 3 download option tabs appear:
 - [ ] tab 1: direct download: mrc format
 - [ ] tab 2: download via cURL: user selects optional save destination and gets presented with cURL command they can copy. note: provide link to how to install cURL
 - [ ] tab 3: download via API: info box to link user to API documentation
   - [ ] P1: surface Dataset ID and Run ID for user to copy
  

Link to design: https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=2315-169420&mode=design&t=8myNEdr3dZigyAP2-0

**Comment by manasaV3** [comment]
```
query download_path {
  tomograms(where: {id: {_eq: <tomogram_id>}}) {
    id
    https_mrc_scale0
  }
}
```

- `download_path.tomograms[..].https_mrc_scale0` can be used to get the path of the tomogram mrc  using curl

- `download_path.tomograms[..].id` can be used to get the tomogram id for the api client

**Comment by junxini** [comment]
pointing reflects reusability aspects

**Comment by Janeece** [comment]
Screenshot from design, for reference:
![Screenshot 2023-11-14 at 1 23 33 PM](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/661c2a5f-af51-4682-92b7-6a3216f70f54)
![Screenshot 2023-11-14 at 1 23 41 PM](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/db5a38df-aa1f-45e7-9037-0755a33c5568)

**Comment by lauramarcos** [comment]
Following bugs were raised while testing this ticket:

No hover state for Download Tomogram / All Annotations [#271](https://github.com/chanzuckerberg/cryoet-data-portal/issues/271)

File Size info is missing in Download Options dialog [#272](https://github.com/chanzuckerberg/cryoet-data-portal/issues/272)

Back button in Download Options dialog is not in correct format according to design [#273](https://github.com/chanzuckerberg/cryoet-data-portal/issues/273)

Error Access Denied when Downloading mcr file [#274](https://github.com/chanzuckerberg/cryoet-data-portal/issues/274)

Command line in Download Options dialog is too close to Copy link, almost overlapping [#277](https://github.com/chanzuckerberg/cryoet-data-portal/issues/277)

Closing this ticket as these bugs will be taking care off in Portal bugs board. Thank you!!!
