### ISSUE TITLE
Download all annotations

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#121]
User story: (5.5) I want to download specific tomograms or annotations so that I have targeted data without unnecessarily using up memory

Tasks
  - [ ] info at the top to show what is being downloaded: dataset name, run name, annotations
  - [ ] 2 download methods via tabs:
    - [ ] tab 1: download via AWS S3
        - _step 1 asks user to select their save destination (this is optional for user) - P1_
        - step 2 is a AWS s3 snippet that user can copy
        - provide link to AWS instructions
    - [ ] tab 2: download via API
      - info box to link user to API documentation
      - _surface Voxel Spacing ID for user to copy - P1_

P1:
- [ ] step 1 asks user to select their save destination (this is optional for user)
- [ ] surface Voxel Spacing ID for user to copy when selecting download via API

Link to design: https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=1929-65448&mode=design&t=8myNEdr3dZigyAP2-0

**Comment by manasaV3** [comment]
```
query download_path {
  tomograms(where: {id: {_eq: <tomogram_id>}}) {
    https_mrc_scale0
    s3_mrc_scale0
    tomogram_voxel_spacing {
      s3_prefix
      run {
        id
      }
    }
  }
}
```

- `download_path.tomograms[..].https_mrc_scale0` can be used to get the path of the tomogram mrc  using curl
- `download_path.tomograms[..].s3_mrc_scale0` can be used to get the path of the tomogram mrc  using aws
- `download_path.tomograms[..].tomogram_voxel_spacing.s3_prefix` can be used to construct the annotation path by adding a `/Annotation` suffix.


- `download_path.tomograms[..].tomogram_voxel_spacing.run.id` can be used to get the run id for the api client

**Comment by junxini** [comment]
pointing is assuming work for #120 is completed and can be reused

**Comment by junxini** [comment]
@jgadling @manasaV3 Anchi clarified the AWS code should include "--no-sign-request" before the AWS code snippet. this is not reflected in the designs 

cc @codemonkey800

**Comment by junxini** [comment]
@jgadling [comment](https://github.com/chanzuckerberg/cryoet-data-portal/issues/59#issuecomment-1796480671 ) about having "--no-sign-request" also applies to this issue.

**Comment by Janeece** [comment]
Screenshot from designs, for reference:
![Screenshot 2023-11-14 at 1 25 01 PM](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/4c626967-9654-41c9-a92c-2d26aeb4662c)

![Screenshot 2023-11-14 at 1 25 33 PM](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/3640e23d-c094-42c3-ab5f-2cd7e40fdb48)

**Comment by lauramarcos** [comment]
Working as expected... thank you!
