### ISSUE TITLE
Single dataset page not opening when clicking on row from Deposition page

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#1215]
**Describe the bug**
Single dataset page should open when clicking on row from Deposition page not only when clicking on Dataset Title

**To Reproduce**
1. Go to https://cryoetdataportal.czscience.com/depositions/10307
2. Click on a Dataset row

**Screenshots**

https://github.com/user-attachments/assets/508cc672-3375-4494-879f-d022d0aadfd8

**Desktop (please complete the following information):**

**Comment by junxini** [comment]
@lauramarcos i think this might have been fixed, could you double check for me?

**Comment by lauramarcos** [comment]
this one is fixed.. closing this bug... thank you!!
