### ISSUE TITLE
Download modal issues: API callout outdated, consistency of font sizes across tabs

### ISSUE THREAD

**Issue by kandarpksk** [chanzuckerberg/cryoet-data-portal#1241]
In the download modal, say when downloading a dataset, there are a couple of issues I noticed in the API tab:
<img width="265" alt="Screenshot" src="https://github.com/user-attachments/assets/881cf5fb-be73-4af0-9850-a5a1698cad08">

1. The callout (text with blue background) to be updated to 
  -  "Prefer to download via our API? Record the code snippet below and visit our API documentation to learn how. "
  -  Link to: https://chanzuckerberg.github.io/cryoet-data-portal/cryoet_data_portal_docsite_quick_start.html
  - note: see Janeece's mockup in comments below

2. "Copy Python code snippet" changed to 14 px size using SDS variable "fontheaderS"

**Comment by Janeece** [comment]
@junxini I finished adding info (above), should be ready to be assigned to eng.

**Comment by kne42** [comment]
everything non-style-related here has been addressed by @melissawm in #1256 

however, the links differ. do we want to use the one in #1256 (https://chanzuckerberg.github.io/cryoet-data-portal/python-api.html) or in this issue @Janeece?

**Comment by Janeece** [comment]
@kne42 thanks for catching this. Use the one in #1256  (https://chanzuckerberg.github.io/cryoet-data-portal/python-api.html) instead!
