### ISSUE TITLE
docs: Add CryoET Workflow article to the docs site

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#1258]
Add a tile for the tutorial on the About CryoET landing page with the following:
CryoET Data Workflow: Overview of the data pipeline from acquisition to analysis

CryoET Workflow Article Content 

- [Copy](https://docs.google.com/document/d/1vK5uxwlP-rPMe68DRKwLh-zif4psHL9J9SLcB73Gncw/edit?usp=sharing)
  - Tutorial body
  - Figure captions
  - Figure alt text
- [Graphics mockups with links to content for embedding where applicable](https://docs.google.com/presentation/d/1mZsZzldukITEY8qManG6YH7MJFB3edVJ29NrcjRwIO8/edit?usp=sharing)
  - use raw HTML where markdown isn’t sufficient for embedding
- [Exported Graphics](https://drive.google.com/drive/folders/1FC1DeiAldD7fQIpjAbzCNAOcWeSw27Ve)
  - [Fig1](https://drive.google.com/file/d/1FLx0OEiIBS0fqNBZxp63vYj4q32JG9MB/view?usp=sharing)
  - [Fig2](https://drive.google.com/file/d/1FGWwzmy6eoJCPEW8b7zLEQxXn5RZnN1a/view?usp=sharing)
  - [Fig3](https://drive.google.com/file/d/1FPpcyoIMdLxa-qxkMl2LEnxFcZQQMifo/view?usp=sharing)
  - [Fig4](https://drive.google.com/file/d/1FebIsdhFfS0sgrD9b33zro7K-5dqcuHE/view?usp=sharing)
  - [Fig5](https://drive.google.com/file/d/1FKrVuSCkyA3gRLdh3u9ZkVbtcRRYGt4q/view?usp=sharing)
  - Fig6-8 are to be directly embedded
  - [Fig9](https://drive.google.com/file/d/1FLjDBaJu2GcnKDGW0WvoqYQQS4pq4cfs/view?usp=sharing)
  - [Fig10](https://drive.google.com/file/d/1Fj9wYbeSvE02WX2o9AMPe8jghdgtSzXc/view?usp=sharing)
  - [Fig11](https://drive.google.com/file/d/1FmRtijPPBYPilJ0Z5ymxQDK-85HqDUoD/view?usp=sharing)

**Comment by melissawm** [comment]
@dgmccart does "directly embedding" mean using the link from the drive? If so, permissions for those files need to be set to public.

**Comment by dgmccart** [comment]
I meant download the video and save it somewhere in this Github repo so that it can be referenced on the page to display the videos.
