### ISSUE TITLE
docs: Update to the docs site before ML Challenge launch

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#1312]
- [x] Update Neuroglancer documentation based on [feedback here](https://docs.google.com/document/d/1pA2cuNsJ3INrzvEPVC_EE2UT5rTG28T-DEDWmNyEuds/edit?usp=sharing) (note tracked changes in the text and feedback section at the top of the doc)
- [x] Update the homepage tile for About CryoET to "About CryoET Data Portal - Learn about CryoET data and how to find and preview it on the Portal"
- [x] Create a [Changelog page](https://docs.google.com/document/d/1s9DwG1ZAO4YhXkVOJbaeSru0kHtRSYh3MnCISf74gek/edit?usp=sharing) (only include content at the top of the doc)
- [x] Create a Data Model page using the content at the top of the python api page and replacing the data model graphic with [this one](https://drive.google.com/file/d/1snFQ_jxtj8Navfb2DHJunm9y7NSR_VCL/view?usp=sharing).
- [x] Create a python API landing page that will open from the top bar nav with 3 tiles detailed in a comment below
- [x] Update the Quick Start Page API Methods Overview Section with the content in the comment below

**Comment by dgmccart** [comment]
On the Python API landing page, replace the bullets with 3 tiles (title - description is the format used below):

 Top left: API Reference - Information on classes and methods (link to API reference page)
 Top right: Data Model - Visualize the relationships between classes in the Python API  (link to the Data Model page)
 Bottom Left: Changelog - Log and migration guide for major API releases (link to the Changelog page)

**Comment by dgmccart** [comment]
In the API Methods Overview Section of the Quick Start page, update the table by alphabetizing, removing classes that do not have download methods, and updating with the new API methods. For reference, the API classes and their download methods are listed below.

Replace the intro sentence: "most classes have download... methods for downloading the data. Below is a table of the API classes download methods." with "some classes have download... methods for downloading the data. Below is a table of the API classes that have download methods." 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-77d980dd-7fff-c029-dacc-00bd111a1556"><div dir="ltr" style="margin-left:0pt;" align="center">
Class | Download Methods
-- | --
Annotation | download, download_metadata
Dataset | download_everything
Run | download_everything
TiltSeries | download_alignment_file, download_angle_list, download_mrcfile, download_omezarr
Tomogram | download_all_annotations, download_mrcfile, download_omezarr
TomograVoxelSpacing | download_everything

</div></b>

**Comment by kandarpksk** [comment]
I also made some updates to the intro text for the data model and API here:
https://github.com/chanzuckerberg/cryoet-data-portal/compare/main...kandarpksk-patch-1

**Comment by melissawm** [comment]
Where should the Changelog page to in the page organization? Under Python API?
