### ISSUE TITLE
View tomogram button at the top of single run page is disabled

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#1360]
**Describe the bug**
View tomogram button at the top of single run page is disabled. This button should be active and clickable

**To Reproduce**
1. Go to (https://cryoetdataportal.czscience.com/runs/16463)
2. Go to view tomogram button at top of page, notice that it's disabled

**Screenshots**

https://github.com/user-attachments/assets/11692fe8-5c81-4ff0-bb22-42eee85e885f

**Comment by jgadling** [comment]
The datasets exhibiting this issue were 10442 and 10440 and they've been updated. The `view tomogram` button should work for all runs now!
