### ISSUE TITLE
[staging] discrepancies in dropdown menus in header

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#151]
**Steps to Reproduce**

1. Click on Tools menu
2. Compare Submenu to design
3. Click on About & Help menu
4. Compare Submenu to design

**Actual Results**

In Tools menu is listed FAQ instead of API 
In About & Help menu is listed API and Submit Feedback

**Expected Results**

In About & Help menu should be listed Report Issue on GitHub and Ask Questions on GitHub

**Design**

<img width="240" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/94851dbd-be4f-457a-be98-efb7ee201d0c">

<img width="358" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/5ef076f7-d38a-48b6-adae-065490c637e0">

**Evidence**

<img width="249" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/56b7166f-6e52-47c7-84b9-481cdde78025">

<img width="270" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/d976104b-758c-46c3-8444-078e901dbc28">

**Comment by Janeece** [comment]
Thats it from my end. Staging reflect the latest designs for the about and help menu.

**Comment by richaagarwal** [comment]
(Updated the github project automation so closing issues will be moved to "Completed" instead of "High severity" going forward 😃)
