### ISSUE TITLE
[staging] Browse Data menu is not in white when clicking on it and also hover state is not working

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#152]
**Steps to Reproduce**
1. Click on Browse Data menu
2. Pay attention to menu
3. Click on Run
4. Pay attention to menu
5. Hover on Browse Data menu

**Actual Results**
Browse Data menu remains in grey at clicked and hover

**Expected Results**
Browse Data should turn white on hover and when user is on:
- browse all datasets/runs
- view single dataset
- view single run

**Design**

<img width="377" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/382ba8a0-e37a-46ce-bc28-26cc176bde27">

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/79d7c622-a0e3-4cb9-8513-4acb3b2fa52c

**Comment by junxini** [comment]
closing as this is fixed
