### ISSUE TITLE
[staging] Legacy links in Footer are opening in new tab and should open in current

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#154]
**Steps to Reproduce**

1. Navigate to Footer
2. Click on Legacy menu located on left side of page
3. Pay attention to where they opened

**Actual Results**
links open in new tab

**Expected Results**
legacy links should open in current tab

**Design**

<img width="379" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/67782f65-6a74-41cd-8f7d-8d9bfad064ad">

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/6ac147a6-3f36-49f4-8031-63beffc1ed6d

**Comment by junxini** [comment]
@lauramarcos closing this as it looks like its been fixed!
