### ISSUE TITLE
Neuroglancer Documentation Needs

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#156]
The connectomics group has a [guide on how to visualize data in Neuroglancer](https://connectomics.readthedocs.io/en/latest/external/neuroglancer.html#basic-usage).

What additional functionality needs documentation for the initial launch?

**Comment by anchi2c** [comment]
We didn't get to do any UXR on Neuroglancer, so we will be o.k. just to provide link to that guide.
