### ISSUE TITLE
UXR study - minor updates for Dec beta release

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#157]
3 small suggestions we're hoping to tweak based on UXR interviews. The interviews are still in progress but there has been enough feedback on the following items that we feel confident moving forward with them.

In prioritized order:
- [ ] add 5 tool tips, in 7 locations. tool tip design and copy [here](https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?node-id=2674%3A14097&mode=dev)
  - [ ] For "Tilt Series Quality" tooltip, there are some small updates (copy, column width) to the labels the tooltips attach to on Single Dataset and Single Run pages.
  - [ ] learn more links are dependent on FAQ copy -- if we do not have FAQ section written, do not include link. (will update if I learn ahead of time to not include)
  - [ ] [SDS tooltip component docs](https://sds.czi.design/009eaf17b/p/74af45-tooltips/t/84dfe9)
- [ ] add a banner to the feedback survey on all pages. feedback survey design [here](https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?node-id=2754%3A25272&mode=dev)
  - [ ] if possible, allow users to dismiss for 2 weeks at a time. if eng bandwidth doesn't allow for this, having the button be not dismissible is fine, just limit it to the Browse all data page
- [ ] add a redundant "more info" button that opens up the metadata panel on the single dataset and single run page. button design[ here](https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?node-id=2674%3A14100&mode=dev)
  - [ ] Uses minimal button to keep number of outlined buttons limited. [SDS minimal button component doc](https://sds.czi.design/009eaf17b/p/47778c-buttons/t/616c45)
- [ ]  remove the number of annotated objects on the single dataset page "runs" table. the object name would stay, just the numbers would be omitted
  - [ ] Column will look the same as it does on All Datasets page

**Comment by junxini** [comment]
@kandarpksk - could you help update this ticket once the tooltips are ready? 
@Janeece - do you have advice on where that button is added and what it looks like?

**Comment by junxini** [comment]
> design and copy is still pending

@kandarpksk to update ticket with newest link and design

**Comment by kandarpksk** [comment]
Janeece and I have discussed the banner design, and she'll be including it in the design review for this ticket. I'm waiting for Anchi's feedback on the banner copy. The link is good to go – it will remain stable even as we update the feedback survey!

![image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/4083860/9b4ace7d-0e2c-43e5-9e05-b9adcf320514)

**Comment by kandarpksk** [comment]
Copy for tooltips:

- Tilt Series Quality: Dataset author’s assessment of tilt series quality. Score ranges 1-5, with 5 being best. Learn More
- Precision: Percentage of true positives among the total number of positive predictions. A value of 100% means everything found is actually the object of interest.
- Recall: Percentage of true positives among the actual number of objects. A value of 100% means all objects of interest were found.
- Ground Truth: Author-curated annotations for use as training or validation data for machine learning models. Learn More (TBD)
- Run: A tomography run is a collection of all data and annotations related to one physical location in a biological specimen. Learn More

**Comment by lauramarcos** [comment]
Following bug raise while testing tooltips.

Tilt Series Quality tooltip is not pointing correctly to text [#254](https://github.com/chanzuckerberg/cryoet-data-portal/issues/254)

Passing this through as it is not affecting any functionality... thank you!
