### ISSUE TITLE
[staging] Check symbol next to text in all filter dropdowns are not centered with text

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#174]
**Steps to Reproduce**

1. Locate filter panel on left side
2. Open [Available Files], [Organism Names], [Object Name] OR [Object Shape Type] dropdowns
3. Hover on their options displayed
4. Pay attention to [✓] located on left side of text

**Actual Results**
[✓] is not centered with text

**Expected Results**
[✓] should be centered with text

**Design**

<img width="249" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/3da924e5-8c97-4cca-890e-420e981bb558">

**Evidence**

<img width="255" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/6d2d6d92-462c-49ca-8fee-da7e63dab47b">

**Comment by junxini** [comment]
@lauramarcos i wasn't able to replicate, could you retest and see if it's still happening on your side?

**Comment by lauramarcos** [comment]
this is no longer repro so closing this one.. thank you!!!
