### ISSUE TITLE
Add new column to annotation table - on single run page

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#177]
Context: Some annotations will have multiple object shape types (e.g., oriented points, segmentation mask). Currently, the only way to differentiate the shape is if the user clicks on the "more info" button to view it in the metadata. In some cases, the annotation name is exactly the same and the user could not tell the difference between them unless clicking into the metadata.  

- [ ] Add object shape type as a table column to the left of "Object Count"

Link to design here: https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=2990%3A30138&mode=dev

**Comment by lauramarcos** [comment]
Object shape type is displayed in column the left of "Object Count". Thank you!
