### ISSUE TITLE
[staging] Application Error page when applying any filter

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#185]
**Steps to reproduce**
1. Click on <Browse Data> menu
2. Click on any filter to personalize Dataset list
3. Error is displayed
4. Go back to app and Refresh
5. Apply any filter
6. Error is displayed
7. Go back to app and click on <CryoEt Data Portal> logo
8. Click on <Browse Data> menu
9. Apply any filter
10. Error is displayed

**Actual Results**
Application Error message is displayed

**Expected Results**
Dataset list must be affected by filter selected

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/2faaf82c-bf6e-4d25-a811-8cf7e18559be

**Comment by richaagarwal** [comment]
@lauramarcos This should be closed per the discussion last week (this was due to schema updates that caused the site to be temporarily down).
