### ISSUE TITLE
[staging] Count in Dataset page is displaying "Runs" instead of Datasets

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#188]
**Steps to Reproduce** 
1. Click on Browse Data menu
2. Pay attention to Count on top of Dataset list

**Actual Results**
It reads "Runs" 

**Expected Results**
Count should read "Datasets"

**Design**
<img width="1181" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/08a905b9-b2c3-4613-a76e-1522a5393286">

**Evidence**
<img width="1546" alt="Screenshot 2023-11-30 at 1 05 33 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/1864b155-8d45-49ac-a9d2-0411971d600d">

**Comment by junxini** [comment]
@lauramarcos i wasn't able to recreate this, could you confirm if it's still showing on your side?

**Comment by lauramarcos** [comment]
@junxini closing this one as it is fixed now... thank you!
