### ISSUE TITLE
[staging] Count is not displaying correct number of Datasets in menu and main panel

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#189]
**Steps to Reproduce**
1.  Click on Browse Data menu
2. Pay attention to Count on top of Datasets list and in submenu

**Actual Results**
It reads "7 of 8 Runs" when there is ONLY 7 Datasets listed and no filters selected

**Expected Results**
If there is ONLY 7 Datasets available should read "7 of 7 Datasets"

**Evidence**
https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/411c5a4d-342d-4bb1-8a7d-0d811a4f956e

**Comment by junxini** [comment]
@lauramarcos could you check if this is still a bug? i think it might have been fixed!
