### ISSUE TITLE
[staging] "AND" logic in "Included Contents" filters is not working as expected

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#190]
According to design, filters in "Included Contents" section should work using the "AND" login when multiselection

**Steps to Reproduce**
1. Locate filter panel on left side
2. Check the <Ground Truth Annotation> filter
3. Click on <Available Files> and select "Raw Frames"
4. Click on <Number of Runs> filter and select ">100"

**Actual Results**

<img width="677" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/316bc177-c49b-4f13-be69-eb6e75718364">

**Expected Results**
According to Filters, the only value that has NO <Ground Truth Annotation> value is Dataset with "0100 Runs", so, when we check the filter, values displayed in main panel are correct when no showing this Dataset... but when we select any value from <Number of Runs> filter excepting ">200", as per using "AND" logic, Dataset with "0100 Runs" should be included in the Results list 

**Design**

<img width="665" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/14211f8f-cbc4-4207-a62d-8f48edcd0454">

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/f6eaad7a-4858-4eb5-a992-c08c9ff2b011

**Comment by junxini** [comment]
@lauramarcos could you double check and see if this is still a bug? i'm not sure i follow the expected results description

**Comment by lauramarcos** [comment]
@junxini Im closing this one as when raised I was not familiar with this conditions but this one is working as expected. Thank you!!!
