### ISSUE TITLE
[staging] "Limit one value per field" instead than "Limit one value per input" in Author filter

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#191]
**Steps to Reproduce**
1. Locate filter panel at left side of page
2. Click on <Author> filter
3. Pay attention to text in dropdown and compare to design

**Actual Results**
"Limit one value per filed"

**Expected Results**
"Limit one value per **input**"

**Design**

<img width="282" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/e3689e18-9426-486d-b7e5-09aa9f72bee3">

**Evidence**

<img width="299" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/1812ffbe-5378-4bc5-88d2-1746a216f855">

**Comment by junxini** [comment]
@Janeece do you remember if the subtext is purposefully different between "Dataset ID" and "Author" filters? If not, maybe we go with `Limit one value per field`

<img width="405" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/98626158/25ebe00c-6c13-43ce-a2de-a9a7a123d0e1">

**Comment by Janeece** [comment]
Yeah, that inconsistency was an oversight. 

@junxini @lauramarcos Lets go with `Limit one value per field`, as Jun suggested. I've updated the design file.

**Comment by lauramarcos** [comment]
Awesome @Janeece, closing this one... thank you!!
