### ISSUE TITLE
Documentation Tasks H1 2024

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#199]
**API**

- [x] P0: Example workflows (e.g. Download the data and run these commands to get the structure of a ribosome; using object relationship such as how to search all tomograms from the same camera model that produces its companion tilt series; API examples to filter <datasets, runs, tomograms, annotations> using <annotation metadata>)
- [x] P0: Update examples using functions within the API documentation in light of the new portal website and the increased availability of data
- [x] P0: Add missing information in the API (e.g. some metadata do not have complete information)
- [x] P1: Rewrite descriptions in the API - Expand on class properties like voxel_spacing, mapping and incorporating information from the schema doc such as units, possible values, matching data schema etc. (note: waiting on feedback from grantees)
- [x] P1: How to download data via API (improve existing  + examples using modals providing IDs)
- [x] P1: Reorganize existing documentation to better guide API users (incl. a summary table of available functions

**Metadata Clarity**

- [x] P0: Explain what binning is based on; describe how binning for tilt series is not matched to the binning for tomograms  - add to FAQ and API
- [x] P1: Expand on definitions of terms + add tooltips (e.g., precision and recall, ground truth, canonical, runs, tilt series quality, method type - curated, manual, predicted)
- [x] P1: info popups when hovering with link to further documentation
- [ ] P?: Newline delimited json (.ndjson) information on format and how to use
- [x] P2: Metadata structure and schema made public directly in Portal (and making sure this becomes the source of truth or is aligned with the SOT)
- [x] P2: Document navigating the portal to demonstrate the database organization and file structure (with examples)
- [x] P2: Audit Data Portal for improved UI documentation (tooltips, popups)

**How To**

- [x] P1: How does the search function work
- [ ] P2: Explain the data contribution process
- [ ] P2: Document how to use [GraphQL](https://github.com/hasura/graphqurl#installation) as an alternative to API
```
brew install node
npm install -g graphqurl
gq https://graphql-cryoet-api.cryoet.staging.si.czi.technology/v1/graphql -i #where should this point
```
- [x] P2: Where to ask questions that allow anyone in the community to answer (note: need to find location for this)

**Visualization**

- [ ] P0: How to view tomograms and annotations in Neuroglancer (having our own writeup instead of external link) 
- [ ] P1: Update how to install/use CryoET napari plugin to reflect any changes 
- [ ] P1: clarify which browsers UI and NG will work with
- [x] P?: What annotations can I view with this tomogram?
- [ ] P2: Add suggestions/descriptions of how to use other plugins - check on compatibility
- [ ] P2: Document how to view tomograms and annotations in desktop tools such as IMOD

**New Documentation Site - Eng Build**

- [x] P0: migrate all docs from prototype site to new UI
- [ ] P2: link to open up a specific accordion
- [ ] P2: how to convert annotation format from ndjson to desired STAR format --> Would need to write converters ourselves; what version is desired.

**Comment by junxini** [comment]
Documentation dependencies: 
**API**
* P0 - Example workflows: Additional metadata getting added (sprint 4), API client improvements (sprint 2)
* P0 - API client changes (GH #320, 321, 322) - sprint 2
* P0 - Missing Info in the API: no dependencies
* Remaining P1's - no dependencies 

**Metadata Clarity**
* P0 - Binning - no dependencies 
* P1 - Expand definitions - no dependencies
* info pop - dependency on Kandarp's UXR summary from Nov 2023. once text and location is identified, Eng can implement. would be good to involve Janeece for design

**How Tos**
* search - dependency on P1 search functionality (Q2'24)

**Visualization** 
* tomogram viewing is ready, annotations viewing is slated for mid Feb
* plugins: work not assigned to sprint yet, we will be improving the plugin UI
* browsers - no dependencies

**Comment by junxini** [comment]
@dgmccart was this meant to be closed out? it looks like the linked PT addressed a subset of the tasks listed here...unless you're planning to migrate the remaining tasks elsewhere?

**Comment by dgmccart** [comment]
Whoops, no I didn't intend to close it. I am still figuring out how everything is linked in github - thanks for flagging this.

**Comment by dgmccart** [comment]
Content has been migrated [here](https://github.com/chanzuckerberg/cryoet-data-portal/issues/766).
