### ISSUE TITLE
[staging] Header objects move and scroll bar disappear when applying some filters

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#200]
**Steps to Reproduce**
1. Click on [Dataset ID] filter
2. Pay attention to header and right scroll bar
3. Click on <Cancel>
4. Header returns to original position and scroll bar shows up again
5. Same for [Author] and [Tilt Range] filters

**Actual Results**
Header elements move and scroll bar on right side of screen disappears

**Expected Results**
Page should not flicker

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/31a30bf4-b913-4733-8ed3-e9d880035d9b

**Comment by junxini** [comment]
@lauramarcos could you check if this is still happening? i think it might have been resolved

**Comment by lauramarcos** [comment]
@junxini yes, this is still happening!

**Comment by junxini** [comment]
@lauramarcos i'm not able to recreate, are you still seeing this?

**Comment by lauramarcos** [comment]
no longer repro... closing this one!
