### ISSUE TITLE
[staging] "AND" logic not working in between Dataset ID's filter

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#203]
**Steps to Reproduce**
1. Click on Dataset IDs filter
2. Enter valid data in Portal ID text field
3. Click on Author filter
4. Enter valid data in Author ID

**Actual Results**
No results were found

**Expected Results**
Following the "AND" logic, results should display Portal ID + Author datasets (2 results)

**Design**

<img width="747" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/bb6d186a-28fd-47f5-bcb8-90d68e77a4da">

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/59dd8ed5-e782-4351-9ba0-ea5546acde0b

**Comment by richaagarwal** [comment]
@lauramarcos I believe this is how the `AND` filter is intended to work across dataset ID and author (as mentioned in the design you shared as well). The `OR` logic would apply only on the other ID fields.  The `AND` means that the results must match on both fields.

**Comment by lauramarcos** [comment]
@richaagarwal so for the AND filter, value entered in Portal ID and Author Name ID should be a match, in case there is not a match including these two values, there will be no results found, is this correct?
