### ISSUE TITLE
Link for users to submit their data - Landing Page

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#204]
- [ ] Direct users to the URL link below when clicking on "share their data" and "Tell us More". https://airtable.com/apppmytRJXoXYTO9w/shr5UxgeQcUTSGyiY?prefill_Event=Portal&hide_Event=true 
- [ ] Correct typo in two places to "Grotjahn"
- [ ] Remove the word "own" from "Find and visualize cryoET datasets in the portal and download to use for your own work." - suggestion from Leah (comms director)

Link to design: https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?node-id=1929%3A65457&mode=dev

**Comment by junxini** [comment]
@kne42 - ticket for the URL links on landing page

**Comment by lauramarcos** [comment]
Moving forward, working as expected. Thank you!!
