### ISSUE TITLE
[staging] "OR" logic seems not to be working in Name/ID filters

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#205]
**Steps to Reproduce**
1. Click on Dataset ID filter
2. Enter a valid Portal ID
3. Enter a valid EMPIAR ID
4. Click on <Apply> button

**Actual Results**
No results were found message

**Expected Results**
Portal ID dataset and EMPIAR ID dataset should be listed in main panel

**Evidence**

<img width="1792" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/71e5170c-dcee-4370-9b0d-4ebf9a52e0be">

**Comment by lauramarcos** [comment]
'OR' logic is now working as expected... thank you!!!

**Comment by richaagarwal** [comment]
@lauramarcos @codemonkey800 I tested this with author and ID fields and it's not working for me. See screenshot. This should return 3 results but it's returning 0 results.

<img width="1292" alt="Screenshot 2023-12-15 at 12 05 37 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/354591/32397a55-47bc-426b-9901-ba218136640c">
