### ISSUE TITLE
[staging] Blue tag [0 - 0] shows up when deleting existent blue tag in Tilt Range filter

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#211]
**Steps to Reproduce**

1. Click on [Tilt Range] filter
2. Enter valid data in both fields, ie. 1 - 100
3. Click on <Apply> button
4. Click on [X] in blue tag
5. Pay attention to what happens when deleting blue tag

**Actual Results**
Blue tag [0 - 0] shows up for a second when deleting previous tag

**Expected Results**
Deleted blue tag should just disappear, second blue tag should not show up

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/399b3e77-50ee-450d-9097-bb570d32af5d

**Comment by junxini** [comment]
@lauramarcos could you check if this has been resolved?

**Comment by lauramarcos** [comment]
no longer repro... closing this one.. thank you!!
