### ISSUE TITLE
Empty field in Reconstruction Method filter

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#213]
**Steps to Reproduce**
1. Locate [Reconstruction Method] filter
2. Click on [Reconstruction Method] filter
3. Hover on top of first option on dropdown
4. Pay attention to shadowed area

**Actual Results**
Seems to be an empty field in dropdown

**Expected Results**
There should not be empty fields in dropdown

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/9152bc1a-eeef-43e9-bc1c-409ed1a47cc7

**Comment by manasaV3** [comment]
Set reconstruction method for dataset id= 10005  to be `None`.

**Comment by manasaV3** [comment]
Also add constraints to the reconstruction method field to not be empty.

**Comment by manasaV3** [comment]
@anchi2c I noticed datasets 10023 and 10024 also have a few runs with an empty string value for reconstruction method. 

This is because the related gjensen datasets (id=33, 34 in file 068.json) have an empty map as value for the tomograms key. How should we handle those?

**Comment by anchi2c** [comment]
I default reconstruction method to "Wighted back projection" and correct bugs that gave multiple reconstruction methods and reconstruction software. in the latest zii-data-portal-processing revision  https://github.com/czimaginginstitute/czii-data-portal-processing/commit/c95da43abfc0150128c0551f20f8ef07fd1e7b53

All json files were updated in this revision affect all tomogram metadata.

**Comment by anchi2c** [comment]
@manasaV3 these json are ready for you to process.

**Comment by manasaV3** [comment]
![Screenshot 2024-04-08 at 11 21 48 PM](https://github.com/chanzuckerberg/cryoet-data-portal/assets/14958785/62adea27-40f2-4256-95a8-803b6e7b9817)

The bug has been fixed in production.
