### ISSUE TITLE
Landing page Bugs from bug bash

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#218]
I tested the page using Google Chrome.

- [ ] Banner dropdowns open in the wrong location sporadically

When opening the Tools and About&Help dropdowns, sometimes the menu displays on the lefthand side of the screen. 
<img width="1508" alt="Screenshot 2023-12-06 at 1 43 01 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/92180364/c7d07bbb-bfbd-4572-b29a-12cb0de8e5e8">

- [ ] Tools menu dropdown has FAQ where it should have a link to the Python API.
<img width="1508" alt="Screenshot 2023-12-06 at 1 47 49 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/92180364/2664cb55-d78e-418a-b10e-a48e3ae7a025">

- [ ] In the About&Help dropdown, the privacy link (this link in the footer also doesn't work) and the data submission policy link go to an error page. 

<img width="1508" alt="Screenshot 2023-12-06 at 1 48 28 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/92180364/ebc20f97-6418-4ecc-b17e-59aabc57ecfd">

- [ ] "or explore via API" link points to the Documentation homepage instead of to the API reference.
- [ ] In the About&Help dropdown, the Report an Issue on Github points to the Github issues page instead of to a blank new issue. Since our users may be inexperienced with Github, we should direct our users to the new issue page to avoid the circumstance where they miss the "New Issue" button.

**Comment by EricMaxWang** [comment]
- [ ] "Privacy" button links to a missing / broken URL
<img width="425" alt="Screenshot 2023-12-06 at 2 07 09 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/100323416/c01b9f76-b68e-4578-be0f-f65e1784cdab">

**Comment by junxini** [comment]
> I tested the page using Google Chrome.
> 
> * [ ]  Banner dropdowns open in the wrong location sporadically
> When opening the Tools and About&Help dropdowns, sometimes the menu displays on the lefthand side of the screen. <img alt="Screenshot 2023-12-06 at 1 43 01 PM" width="1508" src="https://private-user-images.githubusercontent.com/92180364/288556949-c7d07bbb-bfbd-4572-b29a-12cb0de8e5e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTAxNDksIm5iZiI6MTcwMjUwOTg0OSwicGF0aCI6Ii85MjE4MDM2NC8yODg1NTY5NDktYzdkMDdiYmItYmZiZC00NTcyLWIyOWEtMTJjYjBkZThlNWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDIzMjQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMzBiNDQ1YTllYWE3MDFmYjA5ODMzYTJjZDI2MGZkYmFkNjMyNDJhNmFlMTVlOTNkOWZlZGM4OTA3YTZiZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.imfowTMbONlUKRofwQ7qi4iYp83OLnH2MetWdDXZOgs">
> 


**triage check against existing bugs: covered by an issue created by Laura** 

> * [ ]  Tools menu dropdown has FAQ where it should have a link to the Python API.
> 
> <img alt="Screenshot 2023-12-06 at 1 47 49 PM" width="1508" src="https://private-user-images.githubusercontent.com/92180364/288557303-2664cb55-d78e-418a-b10e-a48e3ae7a025.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTAxNDksIm5iZiI6MTcwMjUwOTg0OSwicGF0aCI6Ii85MjE4MDM2NC8yODg1NTczMDMtMjY2NGNiNTUtZDc4ZS00MThhLWIxMGUtYTQ4ZTNhZTdhMDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDIzMjQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjOTBhZDljMzRiNTMyYzU2YjQ2NTAyN2JhNDNkMzFjN2FjNjkzMWI0ZDI0ZDk1OWI0Njk2ZDZmMmEyMWNmOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_jltPtKYkAiCzIGNWyv1TtuYuwzYcJDOhoLIkGNlwY">

**triage check against existing bugs: covered by an issue created by Laura** 

> * [ ]  In the About&Help dropdown, the privacy link (this link in the footer also doesn't work) and the data submission policy link go to an error page.
> 
> <img alt="Screenshot 2023-12-06 at 1 48 28 PM" width="1508" src="https://private-user-images.githubusercontent.com/92180364/288557440-ebc20f97-6418-4ecc-b17e-59aabc57ecfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTAxNDksIm5iZiI6MTcwMjUwOTg0OSwicGF0aCI6Ii85MjE4MDM2NC8yODg1NTc0NDAtZWJjMjBmOTctNjQxOC00ZWNjLWIxN2UtNTlhYWJjNTdlY2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDIzMjQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYjUwMDI3MzM4OTdmOGZkNjY0YzZlMzZkYTk2MGNjOTM0NjUyMWI5NGVlYjBjN2IyNTM3ZjBhNjliYjg5NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nhdh6EVR4sInYhHAusLqbtGMOhHSlMjYemQM7XgIk-8">

**triage check against existing bugs: covered by an issue created by Laura** 

> * [ ]  "or explore via API" link points to the Documentation homepage instead of to the API reference.

**created new bug ticket #263 to reflect this**

> * [ ]  In the About&Help dropdown, the Report an Issue on Github points to the Github issues page instead of to a blank new issue. Since our users may be inexperienced with Github, we should direct our users to the new issue page to avoid the circumstance where they miss the "New Issue" button.

**created new bug ticket #264 to reflect this**

**Comment by junxini** [comment]
> * [ ]  "Privacy" button links to a missing / broken URL
> 
> <img alt="Screenshot 2023-12-06 at 2 07 09 PM" width="425" src="https://private-user-images.githubusercontent.com/100323416/288561444-c01b9f76-b68e-4578-be0f-f65e1784cdab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTAxNDksIm5iZiI6MTcwMjUwOTg0OSwicGF0aCI6Ii8xMDAzMjM0MTYvMjg4NTYxNDQ0LWMwMWI5Zjc2LWI2OGUtNDU3OC1iZTBmLWY2NWUxNzg0Y2RhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QyMzI0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTNkNmNiM2MyY2JkN2I4NzBhMDE5NTA0ZTExNGM0MmEyNWU3N2Y1ZDI4ZDliOTY5OTkyMGU4Nzg3YjlmNjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JgaIteUbHhdLNOQrMSW3bFPySyhBsm1PA5rSWnTvvn8"> <img alt="Screenshot 2023-12-06 at 2 08 19 PM" width="515" src="https://private-user-images.githubusercontent.com/100323416/288561595-4e271cb9-79e2-459f-ae74-37b76126e4a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTAxNDksIm5iZiI6MTcwMjUwOTg0OSwicGF0aCI6Ii8xMDAzMjM0MTYvMjg4NTYxNTk1LTRlMjcxY2I5LTc5ZTItNDU5Zi1hZTc0LTM3Yjc2MTI2ZTRhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QyMzI0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2FkMmQzZGNjNzBiMTgyODYzMDI0MDI5ZmY2NTI2ZmY4YjA0OWRkODJmN2IwNDljNWU5YzVhYjMyZDc1NjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ffy5uDf6YCM4cztjxXXmPwRyElv9_4Owst_1UODHJ0o">

**this is working now**

**Comment by junxini** [comment]
> * [ ]  numbers in the Landing Page text does not match up with the graphic
> 
> > The portal provides biologists and developers open access to high-quality, standardized, annotated data they can readily use to retrain or develop new annotation models and algorithms. Currently, the portal contains **13,861 tomograms** from **53 datasets** contributed by the groups of Julia Mahamid, Jürgen Plitzko, David Agard, John Briggs, Abhay Kotecha, Ben Engel, Danielle Grotjahn, and Grant Jensen.
> 
> <img alt="Screenshot 2023-12-06 at 2 11 46 PM" width="431" src="https://private-user-images.githubusercontent.com/100323416/288562374-c7a50155-a0f8-435b-8643-9d168b6bb883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTAxNDksIm5iZiI6MTcwMjUwOTg0OSwicGF0aCI6Ii8xMDAzMjM0MTYvMjg4NTYyMzc0LWM3YTUwMTU1LWEwZjgtNDM1Yi04NjQzLTlkMTY4YjZiYjg4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QyMzI0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2IzNWI3ZGFiMjUyNTMxOTYwNDUyZDI2OTVkOWU3NWY3NWZkMzBlNDkzN2Y4NTk2MGIyYjk3NDI3MTU0ZWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8xE9VJ8J2uxfPoT3A0U5JzqFcHGPbIId10hor2AsEuw">

**this is covered in a separate ticket that Kira is working on to automate the numbers inline to auto reflect**

**Comment by junxini** [comment]
> * [ ]  redundant sentences are bolded
> 
> > **We are actively growing the number of annotated datasets on the portal and encourage researchers to [share their data]**(https://airtable.com/apppmytRJXoXYTO9w/shr5UxgeQcUTSGyiY?prefill_Event=Portal&hide_Event=true). **We are actively growing the number of annotated datasets on the CZ Imaging Institute portal and encourage researchers to share their data.** We are working with [EMPIAR](https://www.ebi.ac.uk/empiar/) to host the data and support annotation.

**created ticket #240 to capture this**

**Comment by junxini** [comment]
closing this ticket from the bug bash as they have either been closed or reflected in individual bug tickets. Thank you @dgmccart and @EricMaxWang!
