### ISSUE TITLE
Browse All bugs from bugbash

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#219]

**Comment by uermel** [comment]
"Runs" column: total number of runs is filled up to 4 digits with zeros.

<img width="115" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/6641113/da07619b-63b5-476d-bede-88555b622916">

**Comment by uermel** [comment]
Some test output in the list of objects when hovering over "X more objects" in the "Annotated Objects" column

<img width="401" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/6641113/05d5f84e-c8b0-4e12-beb7-bf9cfcff38a0">

**Comment by uermel** [comment]
Not sure if bug: Clicking on the blue "+X more" next to the author list opens the Browse Dataset page. I would have expected to expand the list of authors instead.


https://github.com/chanzuckerberg/cryoet-data-portal/assets/6641113/c1682963-5538-4609-a31d-feba719c147d

**Comment by jgadling** [comment]
This isn't working -- it needs to compare the range to the tiltseries.tilt_range field

**Comment by uermel** [comment]
The EMPIAR ID filter seems not to work on certain entries that it should display, and causes other run to be displayed.


https://github.com/chanzuckerberg/cryoet-data-portal/assets/6641113/a15985c4-1596-480e-bd74-8ca2f0103888

**Comment by uermel** [comment]
Dataset IDs can be searched with glob patterns, but EMPIAR IDs cannot. 


https://github.com/chanzuckerberg/cryoet-data-portal/assets/6641113/9debf11d-626b-4e35-a850-24d7a4e69077

**Comment by uermel** [comment]
EMDB ID-Filter does not work at all. Neither with purely numeric input, nor with EMD- prepended, nor with just EMD.


https://github.com/chanzuckerberg/cryoet-data-portal/assets/6641113/855cbe6f-281d-4086-adc3-a16793cd1c68

**Comment by uermel** [comment]
Reconstruction method filters have one option in all-caps and one in mixed capitalization. This field has controlled vocabulary according to the schema: "Weighted backprojection" "SART" "SIRT"


<img width="291" alt="Screenshot 2023-12-06 at 2 50 12 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/6641113/c103c866-cc0e-4795-a2ae-8c07c1363914">

**Comment by Janeece** [comment]
Object name Overflow tooltip seems to have placeholder object names

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/68b0e821-8210-434e-87d0-07b636a04538)

**Comment by Janeece** [comment]
I think there are missing spaces in the object shape type filter list:
- Segmentation Mask
- Oriented Point


![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/218acf38-1ede-4425-abf0-06daa5d53fa9)

**Comment by Janeece** [comment]
Tilt Range filter "Apply" button should be disabled until user adds/makes a change to either value

**Comment by Janeece** [comment]
There are 2 Gatan options in camera manufacturer filter, one title case and one all caps

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/4fe7cfb9-c71c-46f0-97d1-1abfe2d928ba)

**Comment by Janeece** [comment]
May help clarify how search works to change default text to "Search Dataset Name"?


![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/d1490831-1a3b-476e-99b4-932a7f353418)

**Comment by Janeece** [comment]
Runs tooltip doesnt align with run column if browser window is narrower. Would expect it to change alignment if it needs more space.

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/7a826db9-6013-4a2c-8dcc-52f5bd3faedc)

**Comment by junxini** [comment]
> "Runs" column: total number of runs is filled up to 4 digits with zeros.
> 
> <img alt="image" width="115" src="https://private-user-images.githubusercontent.com/6641113/288557534-da07619b-63b5-476d-bede-88555b622916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTE4OTMsIm5iZiI6MTcwMjUxMTU5MywicGF0aCI6Ii82NjQxMTEzLzI4ODU1NzUzNC1kYTA3NjE5Yi02M2I1LTQ3NmQtYmVkZS04ODU1NWI2MjI5MTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMjM1MzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JiYzE4OTM4NGM5ZWUxYjEwZjg1NmNhOThiOTdkODViZDc2OWQwZDI1Y2M3MTE5NGM1ZWUyNTQ1YjA2NjhjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VfNkp3Eit7I7ierI_URD9Q630XZ5VGpp70IZ_Mz976o">

**created ticket #265 to capture this**

**Comment by junxini** [comment]
> <img alt="Screenshot 2023-12-06 at 1 50 18 PM" width="1510" src="https://private-user-images.githubusercontent.com/475208/288557872-f17ca49a-e016-4f6f-a35a-e0aa7398c7db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTE4OTMsIm5iZiI6MTcwMjUxMTU5MywicGF0aCI6Ii80NzUyMDgvMjg4NTU3ODcyLWYxN2NhNDlhLWUwMTYtNGY2Zi1hMzVhLWUwYWE3Mzk4YzdkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QyMzUzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGIyZTg3MTU1YjAyZDZhN2E0ZGM3OTdjMjQ2YWFjMmFkMmFkMTY4N2ExZmEzNWNhNzI1MGU2Y2ViZjM4YzRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s5cf7KmeEm2A8W6xxE5G753e5PxPSlNxlIlhR4DXVA4">
> The far right column is pushed off the edge of the screen (probably because the description of the datset is so long)

I wasn't able to recreate this but will keep this in mind in case it shows up again. will hold off on creating a new bug for now

**Comment by junxini** [comment]
> Dataset table does not self-adjust to screen size and wiggles around.
> 
>  Screen.Recording.2023-12-06.at.1.52.02.PM.mov

we weren't able to get around to auto resizing for this phase so instead of creating a bug, i'll just log this as something to consider for H1 work

**Comment by junxini** [comment]
> <img alt="Screenshot 2023-12-06 at 1 55 03 PM" width="484" src="https://private-user-images.githubusercontent.com/475208/288558928-6a53a997-dcf3-497b-ab7d-061856e8935a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzE5NTEsIm5iZiI6MTcwMjUzMTY1MSwicGF0aCI6Ii80NzUyMDgvMjg4NTU4OTI4LTZhNTNhOTk3LWRjZjMtNDk3Yi1hYjdkLTA2MTg1NmU4OTM1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQwNTI3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODI1ZjgxNzkyMGRjMzVmMDZlZTBiYjFlM2FkYzYwYTI0ODk2MDI0NzE5MjZjOTg1OTc0ODE1NTllYTI4MmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UjxcAKixZRURpfeYq-dxYMj1_4ceDzCg8rtth3pfGpk"> The "no results found" message looks like it needs more spacing between it and the horizontal line above it

created #267 to capture this bug

**Comment by junxini** [comment]
> 1. Some test output ("A really long name ...") in the list of objects when hovering over "X more objects" in the "Annotated Objects" column


**this has been logged as an existing bug**

> 2. The number of displayed objects is larger than 12, contrary to the label.
> 
> <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/6641113/288559590-05d5f84e-c8b0-4e12-beb7-bf9cfcff38a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzE5NTEsIm5iZiI6MTcwMjUzMTY1MSwicGF0aCI6Ii82NjQxMTEzLzI4ODU1OTU5MC0wNWQ1Zjg0ZS1jOGIwLTRlMTItYmViNy1iZjljZmNmZjM4YTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMDUyNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmRmZWQ3MWZkNjRhZmJiMzQxMTY2NjdiZjk1YjdjZDRhMzQyMDk1ZDk5MDNlNGI0YWIxNzBmYTgwNGI2N2I4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P6Fmpy7L3CA8_rc1_X8WoOzZbo8fHNrvLFuZHw_k9wI">


**created #268 to reflect this bug**

**Comment by junxini** [comment]
> Not sure if bug: Clicking on the blue "+X more" next to the author list opens the Browse Dataset page. I would have expected to expand the list of authors instead.
> 
>  Screen.Recording.2023-12-06.at.2.09.57.PM.mov

** this is expected behavior so that we can keep each row a consistent height without having to account for a really long list of authors

**Comment by junxini** [comment]
> ![Image](https://private-user-images.githubusercontent.com/475208/288563509-e2737493-f27c-440e-b4dd-90b15a1fe5f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzM2MDcsIm5iZiI6MTcwMjUzMzMwNywicGF0aCI6Ii80NzUyMDgvMjg4NTYzNTA5LWUyNzM3NDkzLWYyN2MtNDQwZS1iNGRkLTkwYjE1YTFmZTVmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQwNTU1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWRkYjkyYzZiZmYyYTM3YzBjYmE2NzZmN2RlMzkxOTRmMDA1NTEzNmRkYmUxYThiNTcxZDMyNmQ2ZTAxNWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7TA_45m0yPVmcFBOig7EAyRazdJaVCPLRwgYnvJr3AE)
> 
> The tilt range filter isn't working -- it needs to compare the range to the `tiltseries.tilt_range` field

**Created #269 to reflect this bug**

**Comment by junxini** [comment]
> The EMPIAR ID filter seems not to work on certain entries that it should display, and causes other run to be displayed.
> 
>  Screen.Recording.2023-12-06.at.2.16.23.PM.mov

**Created #270 to reflect this bug**

**Comment by junxini** [comment]
> "Organism Name" search box behaves strangely when scrolling on page.
> 
>  Screen.Recording.2023-12-06.at.2.31.57.PM.mov

**I'm not certain this is a bug but will tag @Janeece to confirm**

**Comment by Janeece** [comment]
> > "Organism Name" search box behaves strangely when scrolling on page.
> > Screen.Recording.2023-12-06.at.2.31.57.PM.mov
> 
> **I'm not certain this is a bug but will tag @Janeece to confirm**

@junxini  I don't think this is a bug, this menu should show to the side where it has space to display (as shown). 

There might be some changes we'd want to consider making to how it displays/behaves while scrolling (ex: should it flip or stay put after opening?), but I would say thats a potential design refinement.

**Comment by junxini** [comment]
> Filtering "Yes" yields two datasets (that don't have fiducials) and filtering "No" yields 4 datasets. 4+2 != 10 (total number of datasets).

Created ticket #290 to capture this

**Comment by junxini** [comment]
> Reconstruction method filters have one option in all-caps and one in mixed capitalization. This field has controlled vocabulary according to the schema: "Weighted backprojection" "SART" "SIRT"

Created ticket #304 to capture this

**Comment by junxini** [comment]
> Tilt Range filter "Apply" button should be disabled until user adds/makes a change to either value

covered in ticket #208

**Comment by junxini** [comment]
> There are 2 Gatan options in camera manufacturer filter, one title case and one all caps

this was fixed

**Comment by junxini** [comment]
> Runs tooltip doesnt align with run column if browser window is narrower. Would expect it to change alignment if it needs more space.

@Janeece should this be part of the responsive behavior work instead of logging it as a one off bug? that way this behavior can be accounted for across all tooltips

**Comment by junxini** [comment]
All bugs listed here have been accounted for, either as new tickets or cross-referenced to existing bugs created by Laura. See inline responses above for more details

**Comment by Janeece** [comment]
> > Runs tooltip doesnt align with run column if browser window is narrower. Would expect it to change alignment if it needs more space.
> 
> @Janeece should this be part of the responsive behavior work instead of logging it as a one off bug? that way this behavior can be accounted for across all tooltips

@junxini we could be group this refinement into the responsive behavior scope of work
