### ISSUE TITLE
Browse all data (list view & pagination)

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#22]
**User story:** (2.1) I want to browse all data, so that I am aware of what is available

**Tasks** 
- [x] Show dataset in list view
- [x] pagination 

**Link to design:** https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?mode=dev

**Comment by junxini** [comment]
@codemonkey800 - here's the backend ticket for author ordering which would apply to the list view https://github.com/chanzuckerberg/cryoet-data-portal/issues/100

**Comment by junxini** [comment]
@codemonkey800 - another backend story where you'll find the key photos #56

**Comment by lauramarcos** [comment]
Im opening this one as Pagination cannot be tested in current staging site @codemonkey800
