### ISSUE TITLE
Single Dataset bugs from bug bash

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#220]

**Comment by Janeece** [comment]
Missing links in Sample & Experiment Metadata (Organism Name, Tissue Name, Cell Name, Cell Line/Strain) ![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/64a2d4d3-4ac3-4f20-9018-e34cd51983f5)

Expected:
Each links to its reference entry
- Organism Name to NCBI entry
- Tissue Name to UBERON
- Cell Name to Cell Ontology
- Cell Line/Strain to NCBI

**Comment by Janeece** [comment]
**Issue:**
- Space between runs table and pagination is missing

**Expected behavior:**
- Space between table and table pagination is space-xxl

**Suggested Priority**
Low

**Image:**
![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/431af844-4360-4eea-8e02-58ce8cec4082)

**Comment by jgadling** [comment]
![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/475208/1560f183-d789-46b3-be48-255b87390a70)



The S3 sync command needs to be updated to include the `--no-sign-request` flag:

```
aws s3 --no-sign-request sync s3://cryoet-data-portal-public/10007/ . 
```

**Comment by junxini** [comment]
metadata panel should not have the field "affiliation name"

**Comment by Janeece** [comment]
Issue:
- when dataset info panel is open, there should be an overlay (same as download dialog), but there is no overlay
- should be true for all panels
- this was added late to the design

Suggested priority:
low

**Comment by Janeece** [comment]
**Issue:**
To navigate to a single run, I must click on the run name as my only option

**Expected Behavior:**
I can click on any part of the first column cell to to open a single run, including keyphoto image

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/d9e6f505-8cde-43be-a6e4-03d985e8c066)

**Comment by Janeece** [comment]
dataset 10005, "DOI" shows twice, in label and in link

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/48c52a7c-ac43-429f-bba4-d0403273729c)

**Comment by Janeece** [comment]
Dataset 10005 doesnt have any primary authors -- is this correct?


![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/013e8a8f-6951-4933-85ca-096ef35a5007)

**Comment by Janeece** [comment]
Dataset 10009 doesnt seem to have complete data

**Comment by Janeece** [comment]
In Runs Table, "Tilt Series Quality Score" header cell label should be updated to "Tilt Series Quality"

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/00547a46-e9b3-45a8-a50d-928492467b4f)

**Comment by junxini** [comment]
> metadata panel should not have the field "affiliation name"

covered in #249

**Comment by junxini** [comment]
> **Issue** If there is no publication, shows empty.
> 
> * dataset 10007 doesnt show any publication
> 
> **Expected behavior** Display "Not Submitted", same as Related Databases

created issue #305 to track this

**Comment by junxini** [comment]
> When clicking on View Tomogram, neuroglancer seems to be having trouble loading
> 
> * dataset 10007

created bug #306 to capture this

**Comment by junxini** [comment]
> Under publications "DOI" shows twice, in label and in link on most datasets

created #307 to capture this

**Comment by junxini** [comment]
> In Runs Table, "Tilt Series Quality Score" header cell label should be updated to "Tilt Series Quality"

created #308 to cover this

**Comment by junxini** [comment]
All bugs have been accounted for by either creating a new ticket or referencing an existing ticket. See comments in line

**Comment by Janeece** [comment]
> > Dataset 10007 the run name is longer than the field displayed in single dataset page. The run names are different only at the end part, so it does not work well when browsing. https://frontend.cryoet.staging.si.czi.technology/datasets/10007?prev=%2Fbrowse-data%2Fdatasets
> 
> @Janeece do you think this can be addressed as part of the text overflow / responsive behavior work?

@junxini it would for sure!
