### ISSUE TITLE
Single Run bug from bugbash

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#221]

**Comment by anchi2c** [comment]
Dataset 10007 single run More Info page tilt range shows keys not values
https://frontend.cryoet.staging.si.czi.technology/runs/528?prev=%2Fdatasets%2F10007%3Fprev%3D%252Fbrowse-data%252Fdatasets&tab=metadata
<img width="501" alt="run-info-tilt-range" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/35783766/7f2fef77-e482-4819-8e3c-7769bea215c0">

**Comment by manasaV3** [comment]
The count of annotation files is not getting reflected correctly
<img width="563" alt="Screenshot 2023-12-06 at 2 24 50 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/14958785/a3b6b2d2-329f-4f26-9940-2424ae935898">

**Comment by manasaV3** [comment]
The samplings available should be sourced from `runs.tomogram_voxel_spacings.voxel_spacing`. It looks like it is currently hardcoded. 
<img width="607" alt="Screenshot 2023-12-06 at 2 32 14 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/14958785/29277554-0be2-450b-b2d8-d4cb98c493f9">

**Comment by manasaV3** [comment]
In the annotations table, we have multiple entries for the same annotation shape in the case of `SegmentationMask`. We have an entry for both mrc and zarr. We should group on the type, and dispaly mrc over zarr. 

<img width="1463" alt="Screenshot 2023-12-06 at 2 39 17 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/14958785/036114ad-d898-46f7-be2d-1f571a748560">


Example: https://frontend.cryoet.staging.si.czi.technology/runs/123

**Comment by manasaV3** [comment]
The annotations have duplicate records in the database. 
Ex: 
```
query MyQuery {
  runs(where: {id: {_eq: 148}}) {
    tomogram_voxel_spacings {
      annotations {
        id
        object_name
        object_description
        object_count
        s3_metadata_path
      }
    }
  }
}
```

**Comment by junxini** [comment]
unable to launch any of the tomograms in Neuroglancer that are under this dataset: https://frontend.cryoet.staging.si.czi.technology/datasets/10005?prev=%2Fbrowse-data%2Fdatasets

**Comment by Janeece** [comment]
Update View Tomogram button icon to the SDS cube icon (should be available now)

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/96386026-198a-40d5-ad21-f4f45aa878eb)

**Comment by Janeece** [comment]
Download diaolog call out shows placeholder IDs


![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/513985b6-d333-48c3-b2a5-b5056a14af1c)

**Comment by Janeece** [comment]
Download dialog should have overline text showing "step 1" or "step 2" (should be available in SDS component)


![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/75eb616d-0a2d-49a2-b6ca-765d0c7a60be)

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/781c3d6d-319b-4600-b67f-68c03cf02390)

**Comment by Janeece** [comment]
On step 2, "back" button should be a secondary button (outline version)

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/0c07b973-5ab9-4b32-9e15-14875cbedda7)

**Comment by anchi2c** [comment]
Download configuration dialog in, for example,
https://frontend.cryoet.staging.si.czi.technology/runs/246?prev=%2Fdatasets%2F10003%3Fprev%3D%252Fbrowse-data%252Fdatasets%26tab%3Dmetadata
1. API documentation link goes to portal home page, not API doc https://chanzuckerberg.github.io/cryoet-data-portal/python-api.html 
2.  ID for the API download in the configuration still TBD.  It should be run ID

**Comment by Janeece** [comment]
Info Panel:
- like in dataset panel , remove affiliation name row
- like in dataset panel, missing links to organism name (NCBI), tissue name (URBERON), Cell Name (Cell ontology), Cell line or strain (NCBI)

**Comment by manasaV3** [comment]
> unable to launch any of the tomograms in Neuroglancer that are under this dataset: https://frontend.cryoet.staging.si.czi.technology/datasets/10005?prev=%2Fbrowse-data%2Fdatasets

@junxini  Because of security concerns, we are not able to expose the data in staging bucket to neuroglancer. So, currently this will only work for datasets that already exist in prod. ie 10000, 10001, 10004

**Comment by Janeece** [comment]
Tilt Series Quality tooltip doesn't align with table cell. Also cell copy should be updated to "Tilt Series Quality".


![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/8e3a30cc-fcc2-4399-8aab-6b2b6227bd3d)

**Comment by manasaV3** [comment]
The unit for TotalFlux is not Å. We should update that in our tiltseries metadata section. 
![Screenshot 2023-12-08 at 2 36 29 PM](https://github.com/chanzuckerberg/cryoet-data-portal/assets/14958785/19c02665-92ec-4aac-b0b8-9fce567a0723)

**Comment by Janeece** [comment]
Issue:
[In prod] precision tooltip has a learn more link, but there is no info to learn more about. 

Expected behavior:
remove learn more link

Screenshot:
![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/57441543-f59e-4f30-bcdd-139e567e9d1e)

**Comment by junxini** [comment]
> When hovering on the tab, the title should say Cryoet data portal.

fixed

**Comment by junxini** [comment]
> Dataset 10007 single run More Info page tilt range shows keys not values 

Captured in bug #333

**Comment by junxini** [comment]
all bugs covered elsewhere or already fixed
