### ISSUE TITLE
Dataset fact check bugs from bug bash 

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#225]

**Comment by uermel** [comment]
Cross-Reference for this issue on browse all: https://github.com/chanzuckerberg/cryoet-data-portal/issues/219#issuecomment-1843808398

Might be related to metadata.

**Comment by uermel** [comment]
Cross-reference for this issue on browse all: https://github.com/chanzuckerberg/cryoet-data-portal/issues/219#issuecomment-1843816712

Might be metadata issue.

**Comment by anchi2c** [comment]
10003 Dataset
https://frontend.cryoet.staging.si.czi.technology/datasets/10003?prev=%2Fbrowse-data%2Fdatasets&tab=metadata
1. more info: tissue name should be None since this is only the bacteria.
2. more info: citation is empty
