### ISSUE TITLE
[staging] Download Dataset button is missing the "..." at the end of label

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#232]
**Steps to Reproduce**
1. Click on a Dataset 
2. Pay attention to "Download Dataset" button

**Actual Results**
Download Dataset button is missing the "..." at the end of label

**Expected**
There should be "..." at the end of button label

**Design**

<img width="229" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/ed365ebb-f770-43d9-96e9-874deb215306">

**Evidence**

<img width="232" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/c84494a4-7be0-4c94-93b6-eff981ee0f31">

**Comment by junxini** [comment]
@Janeece just to confirm, the intent of the "..." is to show that users won't be immediately downloading, but rather have additional steps before initiating download right?

**Comment by Janeece** [comment]
@junxini correct, the "…" is intentional (it was added in a later iteration).

**Comment by lauramarcos** [comment]
[...] are now included in button... thank you!!!
