### ISSUE TITLE
[staging] Able to close "Download Dataset" modal by clicking outside

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#233]
**Steps to Reproduce**
1. Click on a dataset
2. Click on "Download Dataset" button
3. Click outside modal

**Actual Results**
Modal is closed

**Expected Results**
Modal should not be closed by clicking outside of it

**Design**
<img width="716" alt="Screenshot 2023-12-08 at 3 13 55 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/cae97391-7d9a-4d8b-a84c-c7b57ca4bba3">

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/769f1276-0760-4d7f-b309-83b558f97a4c

**Comment by manasaV3** [comment]
Similar to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/260

**Comment by lauramarcos** [comment]
Closing this one so we can follow up on https://github.com/chanzuckerberg/cryoet-data-portal/issues/260, thank you!!
