### ISSUE TITLE
[staging] "View Tomogram" button is not in blue in Single Dataset page

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#235]
**Steps to Reproduce**
1. Click on a dataset
2. Locate Runs section
3. Pay attention to "View Tomogram" button
4. Compare to design

**Actual Results**
Button is in white

**Expected Results**
Button should be in blue and on hover should turn darker blue

**Design**

<img width="625" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/b2caac3d-e27e-4f51-b7ad-617b5dc086d2">

**Evidence**
<img width="1785" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/e9444122-4f69-485b-836f-6d004a410d11">

**Comment by junxini** [comment]
@Janeece i noticed the "view tomogram" button has the white background (matching the staging env) in some of your designs such as "handoff P0 cleanup updates" figma page. could you confirm if this what @lauramarcos logged is expected behavior or a bug?

**Comment by Janeece** [comment]
@junxini @lauramarcos - staging matches the latest design iteration ([here](https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=2325%3A174633&mode=dev), sorry I didnt flag those updates to you earlier.

**Comment by lauramarcos** [comment]
thank you @Janeece Im closing this one then!!
