### ISSUE TITLE
[staging] Pagination is not working when filters are applied

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#243]
**Steps to Reproduce**
1. Locate filter panel on left side of page
2. Click on "Ground Truth Annotation" filter
3. Pay attention to Results

**Actual Results**
For this particular filter, there is only 7 results available and pagination is still displayed

**Expected Results**
Pagination should not be displayed and not functional

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/9a99763d-17d7-4d9c-b304-ccb1db4d2789

**Comment by junxini** [comment]
bug is resolved
