### ISSUE TITLE
[staging] Related Databases list in right panel is not correctly displayed

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#244]
**Steps to Reproduce**
1. Go to https://frontend.cryoet.staging.si.czi.technology/datasets/10000?prev=%2Fbrowse-data%2Fdatasets%3Fpage%3D1%26ground_truth%3Dtrue
2. Click on "More info"
3. Pay attention to EMDB section

**Actual Results**
Extra commas are displayed in between EMDB list

**Expected Results**
Commas should be in between DBs 

**Evidence**

<img width="468" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/956c12fa-f953-455d-b9ee-e72dd0cbc4b6">

**Comment by junxini** [comment]
@lauramarcos i think this is fixed, could you help retest?

**Comment by lauramarcos** [comment]
Extra commas are no longer there... closing this one.. thank you!
