### ISSUE TITLE
[staging] About & Help menu not closing when navigating thru it

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#246]
**Steps to Reproduce**
1. Click on About & Help menu
2. Navigate thru menu

**Actual Results**
Menu dropdown not closing when clicking on any option in menu

**Expected Results**
Menu dropdown should close when clicking on any option in menu

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/43aa438d-1cf8-4788-a3ff-37138b0b209c

**Comment by junxini** [comment]
duplicate of #493
