### ISSUE TITLE
[staging] Some labels in Dataset section in right panel for Single Run page are not per design

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#249]
**Steps to Reproduce**
1. Open a Run single page
2. Click on "More Info" link or button
3. Open Dataset section
4. Pay attention to "Last Modified", "Authors" and "Affiliation Name"

**Actual Results**
It reads "Last Modified", "Authors" and "Affiliation Name"

**Expected Results**
It should be "Last Modified Date", "Author(s)" and "Affiliation Names"

**Design**
https://www.figma.com/file/AELEVptBVyqp0vvFrzgfK6/4---Single-Run?type=design&node-id=33-69033&mode=design&t=gkw21C24JTsEOTlK-0

**Evidence**

<img width="476" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/f0ed95a7-82e9-4397-8dda-c8406e7ded82">

**Comment by Janeece** [comment]
Note: Affiliation Names row should be removed from panel entirely

**Comment by lauramarcos** [comment]
Marking this as medium severity due to @Janeece comment above, thank you!

**Comment by junxini** [comment]
@lauramarcos i think this might be fixed. will you could check please?

**Comment by lauramarcos** [comment]
Last Modified Date is still not reflected in panel and "Affiliation Names" is still displayed and should be removed. This bug remain as opened until this changed are reflected. thank you!
