### ISSUE TITLE
Filter on browse all data page

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#25]
User Story: 2.2 I want to filter through the data, so that I can narrow down my selection

- [ ] 13 filters total, organized within 7 groups (see design) 
- [ ] general AND/OR logic: 
  - AND logic between different filters (e.g., I want to see object name = ribosome AND camera manufacturer = Gatan)
  - OR logic for multiple values within one filter (e.g., I want to see datasets that have Ribosomes OR Membranes annotated)
  - exception to the above rule: multi-select under the "available files" section is AND logic (e.g., i want to see datasets where it includes raw frames AND tilt series) 
- [ ] when filter is applied, show as a blue tag that use can "X" out of to remove
- [ ] only show the filter values that we have available in the database (i.e., we wouldn't list "Mesh" under object shape type if it doesn't exist in our metadata)
- [ ] once filter is applied, show number of search results in the dataset table
- note: see specific filter menu types in design

Link to design: https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=1637-37001&mode=design&t=QGhDNstOreaiFP49-0

**Comment by Janeece** [comment]
Screenshot from Design (for quick reference):

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/9bbe5d93-b6ce-43e3-aa7a-d3f32d0636e8)

**Comment by lauramarcos** [comment]
Following bugs were found during this testing:

Ground Truth Annotation filter is not in correct format and has no hover state [#171](https://github.com/chanzuckerberg/cryoet-data-portal/issues/171)

None of the filters remains shadowed at click and arrow doesn't turn blue as in design [#172](https://github.com/chanzuckerberg/cryoet-data-portal/issues/172)

"Results must include all selected file types:" is missing in [Available Files] dropdown filter [#173](https://github.com/chanzuckerberg/cryoet-data-portal/issues/173)

Check symbol next to text in all filter dropdowns are not centered with text [#174](https://github.com/chanzuckerberg/cryoet-data-portal/issues/174)

**Comment by lauramarcos** [comment]
Passing this item to Completed as bugs opened are taking care of already, no need to track this one here, thank you!
