### ISSUE TITLE
[staging] "Aligned Tilt-Series Binning" is missing in right panel fro Single Run page

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#250]
**Steps to Reproduce**
1. Click on a Run
2. Click on "More Info" button / link
3. Locate Tilt Series section in panel
4. Compare to design

**Actual Results**
"Aligned Tilt-Series Binning" is missing in panel

**Expected Results**
"Aligned Tilt-Series Binning" should be in panel almost at the end of section

**Design**

<img width="317" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/cf346446-6010-46af-82b0-cfc5ff7eb5b1">

**Expected Results**

<img width="447" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/8f334e13-3ff9-4c94-8de2-f68cc0ac4ec5">

**Comment by Janeece** [comment]
Not a bug— this was removed from design after hand-off :)

**Comment by lauramarcos** [comment]
Closing bug as per Janeece's comments, thank you!!!
