### ISSUE TITLE
[staging] Tilt Series Quality tooltip is not pointing correctly to text

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#254]
**Steps to Reproduce**
1. Go to a Single Run page
2. Locate Tilt Series table next to image
3. Hover on "Tilt Series Quality"

**Actual Results**
Tooltip is not pointing to text as it should

**Expected Results**
Tooltip should point to text according to design

**Design**

<img width="461" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/140c5fe3-14a1-490c-ae89-345a2ecb9284">

**Evidence**

<img width="712" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/5d8d9726-5994-4da5-879c-dcbff5860d7c">

**Comment by junxini** [comment]
@lauramarcos i wasn't able to reproduce, could you retest and see if this is fixed?

**Comment by lauramarcos** [comment]
no longer repro... closing this one!! thank you!!!
