### ISSUE TITLE
[staging] "Step 1 of 2" label in Configure Download dialog is missing

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#258]
**Steps to Reproduce**
1. Click on <Download...> button in Single Run Page
2. Pay attention to Title dialog
3. Compare to design

**Actual Results**
"Step 1 of 2" is missing

**Expected Results**
"Step 1 of 2" should be on top of title

**Design**

<img width="416" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/c7c41216-439d-4df6-a8bf-36d701c1d935">

**Evidence**

<img width="598" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/dc00a0a3-50b4-4a0a-8301-1158dee640de">

**Comment by junxini** [comment]
@lauramarcos i think "step 1 of 2" is showing now, do you see it on your side?

**Comment by lauramarcos** [comment]
Yeah... Steps are now showing.. closing bug, thank you!!!
