### ISSUE TITLE
Browse Data Page - Filter "tilt range" not working

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#269]
Per @jgadling The tilt range filter isn't working -- it needs to compare the range to the `tiltseries.tilt_range` field

When adding additional values and selecting "cancel", the numbers are incorrectly displayed 

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/98626158/352b04b6-00d8-49f9-939f-32afd4bf027e)

**Comment by junxini** [comment]
@uermel could you confirm if the max range is 180 degrees?

**Comment by uermel** [comment]
Correct, max range is 180.
