### ISSUE TITLE
Browse Data bug - filters under "Dataset IDs" not working

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#270]
The EMPIAR ID filter seems not to work on certain entries that it should display, and causes other datasets to be displayed.

https://github.com/chanzuckerberg/cryoet-data-portal/assets/98626158/3ce19ea0-bf75-4ce6-ad05-8a46cbd3b56d

**Comment by lauramarcos** [comment]
EMDB filter is now working as expected, thank you!
