### ISSUE TITLE
[staging] Error Access Denied when Downloading mcr file

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#274]
**Steps to Reproduce**
1. Click on [Download...] button in Single Run page
2. Click on Download Tomogram
3. Click on Next
4. Click on [Download Now] button

**Actual Results**
Error Access page is displayed

**Expected Results**
mcr file should be downloaded

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/2c5dbca3-2a1b-482d-9ef1-5230359e4ac1

**Comment by junxini** [comment]
@Janeece agreed, moving this to the medium bucket!

**Comment by richaagarwal** [comment]
@lauramarcos Could you test this on prod?  I suspect there may continue to be some access issues on staging but if it's also an issue in prod, then I agree it's a medium severity @junxini.

**Comment by lauramarcos** [comment]
@junxini in production I am able to download the file

**Comment by junxini** [comment]
the expectation is for users to encounter this behavior when in staging bc the data isn't public. this should not happen in production
