### ISSUE TITLE
Browse all data (show # of datasets)

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#28]
**User story:** (2.1) I want to browse all data, so that I am aware of what is available

**Tasks** 
- [ ] Show total number of datasets

**Link to design:**

**Comment by lauramarcos** [comment]
Count is displayed as expected

**Comment by lauramarcos** [comment]
Reopening due to following: 

Count in Dataset page is displaying "Runs" instead of Datasets [#188](https://github.com/chanzuckerberg/cryoet-data-portal/issues/188)

**Comment by lauramarcos** [comment]
Passing this item to Completed as bugs opened are taking care of already, no need to track this one here, thank you!
