### ISSUE TITLE
[staging] Application Error with Available files filter

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#285]
**Steps to Reproduce**
1. Click on Available Files filter
2. Click on Tomogram option
3. Close dropdown

**Actual Results**
Application Error is displayed

**Expected Results**
Tomogram filter results should be displayed in main panel

**Evidence**

Uploading Screen Recording 2023-12-15 at 2.44.47 PM.mov…

**Comment by junxini** [comment]
Update: 12/15 - team removed the dropdown "tomograms" from this filter to prevent erroring out. the goal is to fix this filter and add in "tomogram" once it's working

**Comment by manasaV3** [comment]
Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/288

**Comment by lauramarcos** [comment]
closing bug as is no longer repro
