### ISSUE TITLE
Add index to tomogram table on the tomogram_voxel_spacing_id field

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#288]
The `tomogram` table doesn't have an index on the field `tomogram.tomogram_voxel_spacing_id` . This field is the foreign key relationship between it and the `tomogram_voxel_spacing` table. So, the join between the two tables is extremely expensive.

**Comment by jgadling** [comment]
All of the foreign key fields have had simple indexes added.
