### ISSUE TITLE
Browse All page filter bug - Fiducial Alignment Status 

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#290]
Per @uermel: The "Fiducial Alignment Status" is a binary filter and is required according to the metadata schema.

Filtering "True" yields 4 datasets (that don't have fiducials) and filtering False" yields 5 datasets. 4+5 != 295 (total number of datasets).

![image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/98626158/71d86cce-43d2-40fe-b29f-dc80fe1cdd98)

**Comment by manasaV3** [comment]
The fiducial alignment field will have to be made a boolean.

**Comment by jgadling** [comment]
Our ingestion scripts have been updated to translate any input values to either 'FIDUCIAL' or 'NON_FIDUCIAL', the DB has been updated to translate any invalid values to valid ones, and metadata has been regenerated and re-sync'd to prod for all tomograms.
