### ISSUE TITLE
Neuroglancer - contrast limit bug

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#291]
Default contrast limit when opening Neuroglancer to view tomogram does not show area of interest. Although advanced users may find a way around it by manually adjusting the contrast limit, most users would not know how to navigate. 

Is there a way to automatically set the contrast to the values that would allow users to see the tomogram as anticipated? 

@uermel this is a rough description above, i'm hoping you can help fill in the gaps!

**Comment by uermel** [comment]
Default contrast limits now are -20 to 20, but we encounter a large range of dynamic ranges in the deposited data. Contrast limits should be set on a per-tomogram basis based on the mean and rms from the MRC header. 

For testing purposes these 5 runs can be used: 

- 10008 - Run “16”: data range ~ -0.5 to 0.5
- 10004 - Run “Position_161”: data range ~ -17000 to 40000
- 10005 - Run “0105”: data range ~ -0.001 to 0.002
- 10007 - Run “ay08102021_grid_1_atc_lamella1_pos11”: data range ~ -16 to 45
- 10059 - Run “dga2018-08-27-600”: data range ~ 0 to 40
