### ISSUE TITLE
Browse All Page - Reconstruction Method Filter Typo

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#304]
**Reconstruction Method filter**: 

- Expected behavior: 3 dropdown options "Weighted backprojection", "SART", "SIRT"

- Current behavior: "FOURIER SPACE", "SIRT" "Weighted backprojection", "Weighted backprojection;SIRT" 

Screenshot: 

<img width="251" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/98626158/93c796ed-7519-4319-b7a5-ec5ffeb6beef">

**Comment by junxini** [comment]
@uermel can you confirm if "FOURIER SPACE" is supposed to be a dropdown option? i see one dataset that lists it as the reconstruction method in the metadata.

Also, can there be multiple reconstruction methods e.g., "Weighted backprojection; SIRT"?

**Comment by junxini** [comment]
@uermel 
i'm not sure if we're keeping this [metadata schema table](https://docs.google.com/document/d/1zcD9OyY86gaogVZOBZPwcn0fxZ5QSFrlqXeaodJX9BI/edit) up to date but if we are, would you be able to add in fourier space?

It looks like "Weighted backprojection; SIRT" was listed as a tomogram reconstruction method hence it showing up as a filter dropdown option. Is this something that needs to be corrected in the metadata then?

**Comment by uermel** [comment]
Yes, I can add that to the metadata table. This particular case does look like a metadata issue in case of the combined methods. @anchi2c Is there a reason you added two different reconstruction methods for these tomograms?

**Comment by manasaV3** [comment]
With the new json being generated by Anchi, we will use that to regenerate the tomogram config. The weighted back tomogram should be used as the Canonical Tomogram.

**Comment by anchi2c** [comment]
I pushed https://github.com/czimaginginstitute/czii-data-portal-processing/commit/c95da43abfc0150128c0551f20f8ef07fd1e7b53 to fix item 2. @manasaV3 this is ready for you.

**Comment by manasaV3** [comment]
![Screenshot 2024-04-08 at 11 21 48 PM](https://github.com/chanzuckerberg/cryoet-data-portal/assets/14958785/62adea27-40f2-4256-95a8-803b6e7b9817)

The bug has been fixed.
