### ISSUE TITLE
Browse All Page - Available Files -> "Raw Frames" filter does not capture all datasets with raw frames

### ISSUE THREAD

**Issue by uermel** [chanzuckerberg/cryoet-data-portal#309]
The available files -> raw frames filter on the Browse All page fails to find dataset 10009 which does have raw frames, finds only 6 datasets.

Expected datasets with frames: 10000, 10001, 10002, 10004, 10007, 10008, 10009

Note that it is possible to find all of the datasets using the API client:

```python
from cryoet_data_portal import Client, Dataset

client = Client()
ds = list(Dataset.find(client, [Dataset.runs.tiltseries.frames_count > 0]))
[d.id for d in ds]
```

Also note that 10009 frames have an unusual file type (.mrc.bz2), which may cause this issue depending on how the filter works?

<img width="772" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/6641113/b4c99c2b-1946-45e6-a841-7f27b773a75c">

**Comment by lauramarcos** [comment]
All expected datasets are now displayed.. thank you!!!
