### ISSUE TITLE
detailed dataset metadata

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#32]
**User story:** (3.4) I want to see detailed dataset metadata, so that I can get information on the experiment as a whole

**Tasks** 
- [ ] ability to expand/navigate for full list of metadata fields

**Link to design:** https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=757-86414&mode=design&t=Vl2vV88PQ7K0PR5R-0

**Comment by lauramarcos** [comment]
[scrolling in right panel is not happening independently ](https://github.com/chanzuckerberg/cryoet-data-portal/issues/149)

[links are missing in "Sample and Experiment Conditions Optional subtitle" section in right panel](https://github.com/chanzuckerberg/cryoet-data-portal/issues/150)

**Comment by lauramarcos** [comment]
Passing this item to Completed as bugs opened are taking care of already, no need to track this one here, thank you!
