### ISSUE TITLE
Update the API client to return lists instead of generator objects for related objects

### ISSUE THREAD

**Issue by jgadling** [chanzuckerberg/cryoet-data-portal#322]
The API client currently returns generator objects for related classes (ex: `dataset.runs`) and this is confusing to our users. Update the client to return a list for these relationships instead.
- Make sure we have unit tests for this functionality
- This *may* prove to be difficult because of the way our API client works. Reach out to Utz/Kandarp if it becomes very sticky and we may choose to update the docs instead of the API client.

**Comment by junxini** [comment]
addressed by https://github.com/chanzuckerberg/cryoet-data-portal/pull/412
