### ISSUE TITLE
Workflow Examples for Documentation

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#329]
Running list of workflows to address in documentation:

- [ ] Download the data and run these commands to get the structure of a ribosome (involved because it includes many sub-tasks) (2 - pipeline is not public) - Utz to follow up about status of this work
- [ ] Using object relationship such as how to search all tomograms from the same camera model that produces its companion tilt series (1)
- [x] Find all datasets/Runs that have raw frames associated with them (1)
- [x] Identify all membrane annotations using GO Terms (1)
- [ ] Download a single tomogram and its associated annotations from s3 - delayed till Feb

Notes: 
3 API improvements identified during Kandarp's UXR session + 1 directly from Utz. Should be completed by mid-Feb. (e.g. allowing download of individual annotations using API) - Jun to share Github ticket

- Download the data and run these commands to get the structure of a ribosome
- most of the annotations are of ribosomes + easy example. Download tomogram + tilt series, start with the tilt series (or could start with the frames), Note: Developing a pipeline for the ML Challenge that could do this
- Using object relationship such as how to search all tomograms from the same camera model (2-3 camera types; each camera has its own characteristics; folks may want to test pipelines using data from different cameras) that produces its companion tilt series
- Building queries based on graphql client. GraphQL is not familiar for many users, so having lots of examples is essential. 
- Find all datasets/Runs that have raw frames associated with them
- For folks who need the raw frames for their process. Frames --> tilt series --> tomograms --> pick particles --> reconstruction based on the tilt series
- Identify all membrane annotations using GO (gene ontology) Terms - all annotations are associated with a GO term; e.g. mitochondrial membrane vs lipid bilayer membrane
- Download a single tomogram and its associated annotations from s3 --> may be blocked by changes to the API client; show difference between .mrc and .zarr formats - show a comparison

**Comment by uermel** [comment]
- [ ] Find all datasets/Runs that have raw frames associated with them
- [ ] Identify all membrane annotations using GO Terms

**Comment by uermel** [comment]
- [ ] Download a tomogram and its associated annotation
