### ISSUE TITLE
all runs associated with dataset (list view)

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#33]
**User story:** (3.5) I want to see all runs associated with this dataset + filter/sort within the dataset so that I can easily navigate large amounts within dataset

**Tasks** 
- [ ] show list of runs

**Link to design:** https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=757%3A86414&mode=dev

**Comment by junxini** [comment]
@codemonkey800 - backend story where you'll find the key photos https://github.com/chanzuckerberg/cryoet-data-portal/issues/56

**Comment by lauramarcos** [comment]
Following defects found:

"Run" title in single dataset page should be in blue and clickable for sorting [#166](https://github.com/chanzuckerberg/cryoet-data-portal/issues/166)

Clickable area taking the user to Run page is not responding [#167](https://github.com/chanzuckerberg/cryoet-data-portal/issues/167)

Tooltips overlap when open one after another [#168](https://github.com/chanzuckerberg/cryoet-data-portal/issues/168)

Clickable area next to "Run"/"Dataset" title is too long [#169](https://github.com/chanzuckerberg/cryoet-data-portal/issues/169)

**Comment by lauramarcos** [comment]
Passing this item to Completed as bugs opened are taking care of already, no need to track this one here, thank you!
