### ISSUE TITLE
Add output schema validation to data standardization

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#338]
Ensures that all the files we write to the data portal's s3 bucket are valid according to our metadata schema spec.

**Comment by richaagarwal** [comment]
@manasaV3 @jgadling What's the status of this one?

**Comment by junxini** [comment]
@manasaV3 i think this needs to go back to the priority backlog right?

**Comment by manasaV3** [comment]
Yeah, this can go back to priority backlog for now.

**Comment by manasaV3** [comment]
This can be closed in favour of https://github.com/chanzuckerberg/cryoet-data-portal/issues/824
