### ISSUE TITLE
There is a refresh hapenning while navigating from page to page and the loader is flashed

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#343]
Steps to Reproduce

1. Go to https://cryoetdataportal.czscience.com/
2. Click on Browse Data
3. Click on a Dataset Name
4. Click on "Back to Results"

**Actual Results**
Loader is displayed for a moment

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/9803268a-0c6b-45ec-b2ae-4fbf1ab2bcc5

**Comment by junxini** [comment]
i think there was a PR that fixed this. could you help verify @lauramarcos?

**Comment by lauramarcos** [comment]
This is no longer showing up.. closing bug.. thank you!
