### ISSUE TITLE
Create FAQ page

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#35]
- [ ] create FAQ page to host documentation
- [ ] allow user to navigate there from the FAQ menu dropdown
- [ ] allow PRs to directly update the text on the FAQ page 
- [ ] each question/section can be collapsed and expanded (accordion style), defaulting to collapsed view when users first navigate to page

Link to design: https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?node-id=2234%3A141854&mode=dev

**Comment by junxini** [comment]
this is newly prioritized now that we have Dannielle's help with documentation. Also because users need to know how to download via AWS

**Comment by junxini** [comment]
@Janeece will be adding designs this week

**Comment by Janeece** [comment]
[SDS Accordion Component Docs](https://sds.czi.design/009eaf17b/p/50d099-accordions)


**Screenshots for quick reference:**
Note: Actual content may vary, designs are intended to give general typesetting styling directions for different type of content. Feel free to reach out to me if need support on how to apply to real content. 

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/ea51d6e5-5e0e-4230-9070-d75db1c1a104)

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/4da82848-3d43-4119-91de-aca163ed4fd4)

**Comment by lauramarcos** [comment]
@codemonkey800 I dont see this in staging, can you please confirm?

**Comment by lauramarcos** [comment]
Sending this one to `Review` status as this is not in staging yet, @codemonkey800 please send it back to `Ready for QA` status when in staging. thank you!!!

**Comment by richaagarwal** [comment]
@lauramarcos The FAQ page is available at https://frontend.cryoet.staging.si.czi.technology/faq (and is linked to from the "About & Help" menu).

**Comment by lauramarcos** [comment]
FAQ page working as expected, thank you!
