### ISSUE TITLE
Create config yamls for new datasets

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#361]
Create configuration yamls to define metadata and sources for CZII-generated datasets.

**Comment by uermel** [comment]
- [ ] 10301 First CZII dataset
- [ ] 10302 Chlamy stub set
- [ ] 10303 Greenan cilia

**Comment by junxini** [comment]
@uermel this was discussed in yesterday's sprint planning session as i believe #357 is dependent on this. i've added you as the assignee, let me know if this is something you were planning to work on in sprint 4 (2/26 - 3/8) cc @manasaV3
