### ISSUE TITLE
Setup infrastructure for running db import using swipe

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#364]
Create infrastructure to run a swipe job in staging and prod to import datasets to the database using swipe. 
Tasks: 
- [ ] Push docker image to staging and prod
- [ ] Setup wdl and other swipe infrastructures with permissions to write to db
- [ ] Create db enqueue job

**Comment by junxini** [comment]
@manasaV3 this was pointed as a 1 because #363 is pointed as a 3. Please confirm if you agree

**Comment by manasaV3** [comment]
@junxini  Updating the pointing on this, as the functionality implemented by this has changed.
