### ISSUE TITLE
[Complete] Data Discovery Improvements V2

### ISSUE THREAD

**Issue by Janeece** [chanzuckerberg/cryoet-data-portal#366]
**In progress**

- https://github.com/chanzuckerberg/cryoet-data-portal/issues/574 / #565 
- #600 
- #713 

**Blocked**

**Comment by kev-zunshiwang** [comment]
Search Design Schedule
Week 4/15 - eng research / scope alignment
Week 4/22 - R1
Week 4/29 - Scitech week
Week 5/6 - R1.5 / 2 days OOO
Week 5/13 - OOO
Week 5/20 - R2
Week 5/27 - Handoff
Week 6/3 - Wrap up details / support implementation

**Comment by Janeece** [comment]
**Search Specs:**
https://www.figma.com/design/o8XTUwgjPSEV6BByf6QiUC/Kevin---Data-Discovery-Improvements-V2?node-id=6701-101833&t=MiKlUkNiPBlNghRF-1

**CTF/Alignment file Specs:**
https://www.figma.com/design/o8XTUwgjPSEV6BByf6QiUC/Kevin---Data-Discovery-Improvements-V2?node-id=6717-8260&t=MiKlUkNiPBlNghRF-1
