### ISSUE TITLE
navigate to single run page on a filtered dataset disables navigation back through bread crump or links

### ISSUE THREAD

**Issue by anchi2c** [chanzuckerberg/cryoet-data-portal#382]
To reproduce this bug:
1. visit browse dataset page
2. add a filter, for example, Tomogram->Reconstruction Method->SIRT
3. select any dataset result to go to runs page
4. select a run in the dataset to go to single-run page
5. click on cryoET Data Portal "Beta" gives a page like this:

<img width="1478" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/35783766/58e26953-1cbc-40d0-b12c-9d4894373870">
URL looks like this:
https://cryoetdataportal.czscience.com/runs/672?prev=%2Fdatasets%2F10030%3Fprev%3D%252Fbrowse-data%252Fdatasets%253Freconstruction_method%253DSIRT

To reset, I had to remove all the part after .com/

**Comment by kandarpksk** [comment]
I'm on this page in both Chrome and Safari: https://cryoetdataportal.czscience.com/runs/12361?prev=%2Fdatasets%2F10141%3Fprev%3D%252Fbrowse-data%252Fdatasets&download-step=configure

In Chrome, the page freezes when I click download. In Safari, the page works, but refreshes in each click on the button or in the modal.

<img width="1800" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/4083860/50a94b5f-0c8d-4126-91c5-b353550b7dc4">

**Comment by lauramarcos** [comment]
page is now responsive in both cases.. thank you!!
