### ISSUE TITLE
Add Metadata field "visualization default" for annotations

### ISSUE THREAD

**Issue by uermel** [chanzuckerberg/cryoet-data-portal#383]
This is required to set default annotations to load for neuroglancer annotations.

**Comment by manasaV3** [comment]
@uermel In the case where an annotation has multiple shapes, should all of them be considered curator-recommended or visualization-default? Or would we want that to apply to a specific shape?

**Comment by uermel** [comment]
They should be false by default. We shouldn't recommend entries by default and also only show annotations when selected.

**Comment by uermel** [comment]
It would be better to apply to a specific shape type (if that's possible).

**Comment by manasaV3** [comment]
Yes, we can do that. :)

**Comment by manasaV3** [comment]
Blocked by https://github.com/chanzuckerberg/cryoet-data-portal/issues/323

**Comment by uermel** [comment]
@manasaV3  See here: https://github.com/chanzuckerberg/cryoet-data-portal-backend/pull/9#issuecomment-1936429165
