### ISSUE TITLE
Update  Samplings Available in Run page

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#394]
The samplings available needs to surface the tomogram voxel spacing associated to the run.

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/14958785/f9f4ffcd-2400-458b-a4ac-10df04215115)

**Comment by junxini** [comment]
hey @manasaV3 - can you remind me why this is blocked?

**Comment by manasaV3** [comment]
@junxini Sorry, I think this got moved into blocked by mistake.
