### ISSUE TITLE
Annotated objects names have duplicates

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#396]
The annotation object names have duplicates due to varying cases.

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/14958785/be0da3f3-0d29-4c05-bfa3-603c77d933bc)

**Comment by uermel** [comment]
From a data perspective this is fixed. We need to reimport the annotation metadata and then do a database import. @manasaV3

**Comment by manasaV3** [comment]
Requires cleaning up of old annotations wherever the annotation object name has been updated with more than text case changes in https://github.com/chanzuckerberg/cryoet-portal/pull/113
