### ISSUE TITLE
Download dialog to include file size - size varies depending on whether it's MRC vs Zarr

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#398]
standardize how file sizes get shown when downloading. for example, when downloading all annotations from the single run page, the file size will change depending on whether its a MRC or Zarr file. Zarr files are only applicable to API download tab. 

The goal is to provide clarity on the file size before they proceed with downloading. Users from the UXR study were cautious of selecting download because CryoET data files can be very large.

Priority = P1

**Comment by Janeece** [comment]
Work + Hand-off file: https://www.figma.com/file/gwX2PjfGPfMrbEWMMJq6rW/H1-2024---Annotations-Table-Update?type=design&node-id=517%3A109287&mode=design&t=yRNUdWtNLkrDBrGk-1

Changes are also being made to other download dialogs. 
Tomogram specific updates: https://www.figma.com/file/gwX2PjfGPfMrbEWMMJq6rW/H1-2024---Annotations-Table-Update?type=design&node-id=679%3A187741&mode=design&t=yRNUdWtNLkrDBrGk-1
