### ISSUE TITLE
CryoET page freezes when clicking on <More info> button in Single Run page

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#409]
**Steps to Reproduce**

1. Go to https://cryoetdataportal.czscience.com/runs/12361
2. Click on <More info> button

**Actual Results:**
CryoET page freezes in chrome. Button is not responsive in Safari and Firefox

**Expected Results:**
Right panel should open

**Evidence**

<img width="431" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/578b8481-9994-4c3d-b7ab-f424978f89af">

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/ce1b90b7-91e7-4a45-96f0-ad60553bf2f2

**Comment by kandarpksk** [comment]
The same behavior happens on clicking the Download button too.

**Comment by lauramarcos** [comment]
Now working as expected, closing this one.. thank you!
