### ISSUE TITLE
Key photo at run level

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#41]
User story: (4.3) I want to see a key photo at the run level, so that I can get a glimpse of what I might expect to see in the run

- [ ] ability to see keyphoto
- [ ] click into keyphoto to expand

Note: right click does not allow due to size of image. will move forward with click to open photo in separate tab

Design: https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=1310%3A11321&mode=dev

**Comment by junxini** [comment]
@codemonkey800 - backend story where you'll find the key photos https://github.com/chanzuckerberg/cryoet-data-portal/issues/56

**Comment by Janeece** [comment]
@Janeece - future (H1 2024 design) -- design to help user understand what will happen when they click. Note: this might be if we implement viewing snapshots first.

**Comment by kne42** [comment]
QA testing blocked by staging environment bug

**Comment by lauramarcos** [comment]
Working as expected.. thank you!
