### ISSUE TITLE
Method type tool tip on annotation table

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#436]
tooltip within the Annotation Table:
- [ ] tool tip when hovering over "Method Type" column header and the 3 possible values within that column - Manual, Automated, Hybrid ([see design here](https://www.figma.com/file/gwX2PjfGPfMrbEWMMJq6rW/H1-2024---Annotations-Table-Update?type=design&node-id=639%3A178860&mode=dev))

dependent on #464

**Comment by dgmccart** [comment]
[Copy is linked in this issue](https://github.com/chanzuckerberg/cryoet-data-portal/issues/464) @kne42
