### ISSUE TITLE
Design improvements to how authors are displayed in portal

### ISSUE THREAD

**Issue by Janeece** [chanzuckerberg/cryoet-data-portal#461]
## Overall Summary:
**User value:** display author information to give proper credit for their work; make author information easily visible and findable

**Bucket of work:** update how Authors are displayed;  link to ORCID (a unique, persistent identifier for researchers that showcases all of their work) 

**What is the design scope:** mockup key patterns, then implement pattern across affected masterfiles 

## Design Requirements

- [x] **P0 - Update author order displayed on "All Datasets" and "Annotations" tables so that it displays primary and corresponding authors.** 
    - Currently, shows [primary authors], [other authors], [corresponding authors], with a button to indicate overflow  ![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/62786307-a2e3-4b55-b6f4-f801eafeefa0)
    - By default: show all primary and corresponding, with “...” in between for the other authors. Example: “primary, primary, primary,.....corresponding, corresponding”  
  - If overflow: Show at least first Primary and last corresponding author ![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/2ae5ec7e-4002-4c7b-9375-86fc8c48626f)
  - **Make a recommendation:**
    - whether or not to remove  “+n more” link that opens page or info panel (Anchi/Utz didnt think it was necessary, Jun/Janeece think it helps provide context about overflow & where to see the overflow)
    - whether or not to carry over corresponding author icon to tables

- [x] **P1 - Provide user with a way to access author ORCID page from locations where all authors are viewable (single dataset page header and metadata panels)**
  - per author name, user can see if there is a link to the ORCID page available
  - if there is an ORCID link, user can click to open in a new tab
  - **Considerations:**
     - how does the design interact with the corresponding author icon that displays in the same area?
     - how do other databases/products handle this? One example pattern is [bioarxiv.org](https://www.biorxiv.org/)

**Comment by kev-zunshiwang** [comment]
Mini spec link: https://docs.google.com/document/d/1Eewt2ls8feK32FT9r0ADtLYpjtI3ooxtafY2UIDDBKc/edit?usp=sharing
