### ISSUE TITLE
Add "Which annotations can I view with the tomogram" link

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#462]
Add text to the upper right corner "Which annotations can I view with the tomogram" this will link out to documentation in 2 places:
- on single dataset page
- on single run page 

([see design here](https://www.figma.com/file/gwX2PjfGPfMrbEWMMJq6rW/H1-2024---Annotations-Table-Update?type=design&node-id=561%3A171504&mode=dev))

dependent on documentation ticket #465

**Comment by junxini** [comment]
will not be added until annotations can be viewed in Neuroglancer

**Comment by dgmccart** [comment]
[This PR](https://github.com/chanzuckerberg/cryoet-data-portal/pull/647) will add a question to the portal site FAQ and duplicate the FAQ content to a new FAQ page on the docsite. Either location can be linked to.

**Comment by junxini** [comment]
no longer needed as we can view all annotations in NG
