### ISSUE TITLE
Tool tip documentation for method type on single run page

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#464]
- [x] tool tip copy for: 
  - hovering over "Method Type" column header 
  - the 3 possible values within that column - Manual, Automated, Hybrid 

([see design here](https://www.figma.com/file/gwX2PjfGPfMrbEWMMJq6rW/H1-2024---Annotations-Table-Update?type=design&node-id=639%3A178860&mode=dev))

Related to #436

**Comment by dgmccart** [comment]
[Copy is here](https://docs.google.com/spreadsheets/d/1QEPiDcjGJYWSZXsbRjwHd9aeZjbk_tvv2UQ4DKyMwxk/edit#gid=339544814&range=3:6), and it has been approved by @uermel
