### ISSUE TITLE
File format tooltip copy

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#466]
- tooltip documentation for the info icon next to "File Format" that describes the file format options

- Dannielle to decide if additional supporting documentation explaining file format is needed (outside of the copy in the tooltip) 

**Link to design:** https://www.figma.com/file/gwX2PjfGPfMrbEWMMJq6rW/H1-2024---Annotations-Table-Update?node-id=527%3A139630&mode=dev

**Comment by dgmccart** [comment]
[Copy is here](https://docs.google.com/spreadsheets/d/1QEPiDcjGJYWSZXsbRjwHd9aeZjbk_tvv2UQ4DKyMwxk/edit#gid=339544814&range=7:7). Approved by @uermel
