### ISSUE TITLE
Fix spacing values for volume data that have incorrect values in headers

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#469]
Some of the volumes that read the voxel/pixel spacing from the source file header have to be reprocessed, as the source data has incorrect MRC headers. 

This relates to https://github.com/czimaginginstitute/czii-data-portal-processing/issues/9

**Comment by richaagarwal** [comment]
@manasaV3 Accidentally closed this earlier - could you clarify if this is still in progress or not?

**Comment by manasaV3** [comment]
@richaagarwal Yeah, this is complete. :)
