### ISSUE TITLE
Various UI/UX issues while viewing certain Runs

### ISSUE THREAD

**Issue by kne42** [chanzuckerberg/cryoet-data-portal#477]
1. go to https://cryoetdataportal.czscience.com/runs/1880
2. click on the download button
3. attempt to click on "Download Tomogram" but it is disabled (maybe this is intentional?)
4. attempt to click on the arrow to collapse the info box but it doesn't work
5. go to the next step and switch to the api tab
6. there is no voxel spacing id to copy

https://github.com/chanzuckerberg/cryoet-data-portal/assets/29165011/3bdf9360-b7b9-454b-b724-945920ee9f55

**Comment by junxini** [comment]
closing as this has been fixed. download tomogram is greyed out when there aren't tomograms present
