### ISSUE TITLE
Incorrect horizontal overflow on configure download dialog

### ISSUE THREAD

**Issue by kne42** [chanzuckerberg/cryoet-data-portal#478]
1. go to https://cryoetdataportal.czscience.com/runs/1414
2. click on download button
3. click on "Download Tomogram"
4. scroll horizontally in the dialog

https://github.com/chanzuckerberg/cryoet-data-portal/assets/29165011/02da56af-ce70-471c-a414-3efe7df0cc54

**Comment by manasaV3** [comment]
@kne42 Is this still an issue?

**Comment by junxini** [comment]
closing as this is resolved
