### ISSUE TITLE
Introduce annotation filters for single dataset

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#486]
**Tasks**:

Add filters to narrow down runs by filtering on annotations.

**Link to design:**  https://www.figma.com/file/q6Z394Xy6wUmaXQ9YFjZH7/Kevin---2023-Spillover-Work?type=design&node-id=2118-11276&mode=design&t=41b8zGhU4oUzctHN-0

**Comment by manasaV3** [comment]
Relates to #34

**Comment by junxini** [comment]
duplicate of #488

**Comment by junxini** [comment]
duplicate of #488
