### ISSUE TITLE
EMPIAR ID link is not working

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#490]
**Steps to Reproduce**
1. Go to Browse All page
2. Click on an EMPIAR ID link

**Expected Results**
Empiar page should be displayed

**Actual Results**
Service Unavailable page is opened

<img width="1451" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/20b8e530-a593-4524-9cce-3c7f64eca0ec">

**Comment by junxini** [comment]
@lauramarcos we can close this since this is outside of our website :)
