### ISSUE TITLE
Organism Name in right panel is not linked

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#491]
**Steps to Reproduce**
1. Click on a Dataset to opened Dataset Single page
2. Click on More info button
3. Pay attention to Organism Name in Sample and Experiment Conditions section

**Expected Results**
Organism Name data should be linked

**Evidence**

<img width="461" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/80cb3b3f-0fc0-4a33-a74d-70a4f364e0ea">

**Comment by junxini** [comment]
@lauramarcos could you retest please?

**Comment by lauramarcos** [comment]
Organism Name is still missing the link! Keeping this one opened

**Comment by junxini** [comment]
duplicate of #150. closing this as not all organism fields are meant to have a link.
