### ISSUE TITLE
Runs are not being sorted in Dataset Single page

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#494]
**Steps to Reproduce**
1. Click on Browse all data
2. Click on a Dataset
3. Locate Runs table
4. Click on "Runs"

**Expected Results**
Runs should be sorted

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/252eba09-05cf-4716-8556-a96f68774fe8

**Comment by junxini** [comment]
@lauramarcos i didn't see the drop down arrow that indicates there's sorting. do you still see it on your side?
