### ISSUE TITLE
Single run page is not opening when clicking on image in Single dataset page

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#495]
**Steps to Reproduce**
1. Click on a dataset
2. Navigate to Runs section
3. Click on an image

**Expected Results**
Single run page is not opened

**Evidence**
<img width="753" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/a3891451-94c7-4329-905b-5d8f450aee46">

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/9bc4edce-a173-495a-a0c3-52450616687b

**Comment by junxini** [comment]
there's a new ticket that improves the click area, marking this as closed.

https://github.com/chanzuckerberg/cryoet-data-portal/issues/621
