### ISSUE TITLE
[Analytics] - Filters, opening and closing the download modal and also the clicking in the tabs inside this modal and right panel not detected by Plausible for Chrome

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#504]
Plausible is not getting following actions when performed in Chrome

Filters
Opening and closing the download modal
Clicking in the tabs inside the download modal
Opening right side panel

https://plausible.io/share/cryoetdataportal.czscience.com?auth=jf9cJeBWiRymfylFkd096&country=MX&country_labels=Mexico&region=MX-NLE&region_labels=Nuevo+Le%C3%B3n&browser=Chrome

<img width="1082" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/9cf11f68-b04f-4ff7-a8c9-6e9b5c7b5e8c">

**Comment by bnelson-czi** [comment]
Seems like it's all or most of the custom goals. Pageview goals are getting recorded correctly though.

**Comment by lauramarcos** [comment]
all actions are now caught correctly by chrome... thank you!
