### ISSUE TITLE
Agree on metadata changes

### ISSUE THREAD

**Issue by jgadling** [chanzuckerberg/cryoet-data-portal#52]
We have a variety of different metadata changes coming up for Phase 2. Before we can make these changes to our json and GQL schema, let's get approval for what these fields should be called and what their structure should be.

Draft changes are here: https://docs.google.com/document/d/1zcD9OyY86gaogVZOBZPwcn0fxZ5QSFrlqXeaodJX9BI/edit#heading=h.be2fyivqz1zp

**Comment by junxini** [comment]
note from sprint planning meeting: Anchi is the main approver
