### ISSUE TITLE
Create common layout components

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#53]
- Header
- Footer
- Slide out drawer

Link to design: https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=598-53839&mode=design&t=0Hm4tGg3ge7Rpmuu-0

Link to logos: https://drive.google.com/drive/folders/1MdDfET-nznjnx5EmO0icHokVq_H2mNo_?usp=drive_link

**Comment by lauramarcos** [comment]
[discrepancies in dropdown menus in header](https://github.com/chanzuckerberg/cryoet-data-portal/issues/151)

[Browse Data menu is not in white when clicking on it and also hover state is not working](https://github.com/chanzuckerberg/cryoet-data-portal/issues/152)

[Tools dropdown menu shows up on left side after clicking on it several times](https://github.com/chanzuckerberg/cryoet-data-portal/issues/153)

[Legacy links in Footer are opening in new tab and should open in current](https://github.com/chanzuckerberg/cryoet-data-portal/issues/154)
