### ISSUE TITLE
Docs: Implement accordions in the API reference

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#577]
The API reference is difficult to navigate since its current organization is a long list. In preparation for the UXR API study, we'd like to improve the navigation of the API reference by implementing accordions for each class so that all classes can be seen at a glance. These accordions should be closed by default.

**Comment by manasaV3** [comment]
Is there any specific reason for wanting the accordions? The links in the left nav bar give us a list of all the classes in the Python API section, and clicking on them should take us to the relevant class.  

Also, having all of the classes expanded would help us use the search more easily to find specific things.

**Comment by junxini** [comment]
can we use the conftrol F function to look for specific text when the accordions are collapsed?

**Comment by kandarpksk** [comment]
We can close this until we learn more after switching to the new theme (https://github.com/chanzuckerberg/cryoet-data-portal/issues/889)
