### ISSUE TITLE
Docs: Add summary table of functions in the API reference

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#578]
The API reference is difficult to navigate since many classes have long lists of attributes that obscure the useful functions in the class. In preparation for the UXR API study, we'd like to help users understand the functions available to them at a glance. 

We'd like to include a summary table of the available functions. This table should have 3 columns: class name, function name and description of the function. This table should be located beneath the data model and above all of the class descriptions.

Ideally, since our API reference is autogenerated, we'd like this table to be autogenerated as well if possible so that changes to the API are immediately reflected in the table of available functions. If this is not possible, code for generating a table in rst files is sufficient, and the table can be manually populated and updated.

**Comment by dgmccart** [comment]
The table could look something like this:
<img width="644" alt="Screenshot 2024-03-13 at 4 54 37 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/92180364/4298bf94-a3d8-43d0-9bcd-eb979606581e">

**Comment by kandarpksk** [comment]
We can close this until we learn more after switching to the new theme (#889)
