### ISSUE TITLE
Download dataset dialog consistency with other dialogs

### ISSUE THREAD

**Issue by Janeece** [chanzuckerberg/cryoet-data-portal#585]
Requestor: @Janeece 

Request:
- download dataset dialog API tag still only shows dataset ID in API tag (all others have code snippet)
- Can we update this to show the download code snippet instead?

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/0ff49b9d-f8ea-4abe-b406-8052777d5deb)

**Comment by manasaV3** [comment]
Captured as a part of https://github.com/chanzuckerberg/cryoet-data-portal/issues/447
