### ISSUE TITLE
Add Breadcrumb

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#592]
Remove the existing back button and replace with breadcrumb above page title to help users navigate through the portal. See all specs in the design link below. 

**Additional note that's not in the design spec**: keep existing filtering behavior where the previously applied filters persist when you go back to the previous page. i believe this is what we have currently in prod. 

Link to design: https://www.figma.com/file/tKMoeyLbzQDLtlyrEzs9uX/Kevin---Data-Discovery-Improvements-V1?type=design&node-id=4681-37698&mode=design&t=PKtwsz7WDdS9W9kz-0

**Comment by manasaV3** [comment]
Carrying back of filters from run to datasets will not be addressed as part of this ticket. @junxini

**Comment by junxini** [comment]
> Carrying back of filters from run to datasets will not be addressed as part of this ticket. @junxini

yep that's accurate :)

**Comment by junxini** [comment]
note: any kind of carryover behavior will be net new build. All carryover behavior will be a part of #527
