### ISSUE TITLE
Configure download dialog from single run page

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#60]
User story: (5.5) I want to download specific tomograms and/or annotations so that I have targeted data without unnecessarily using up memory

Tasks
- [ ] download button on single run page to open "Configure Download" dialog
- [ ] dialog contains the following elements: title, dataset name, run name, and 2 download options (see below)
  - [ ] #120
  - [ ] #121
- [ ] directions to download all run data via API, with link to API instructions

Link to design: https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=2315-169419&mode=design&t=8myNEdr3dZigyAP2-0

**Comment by Janeece** [comment]
Screenshot from designs:

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/07399a04-586d-449d-8b89-9c962c6643db)

**Comment by lauramarcos** [comment]
Following bugs were raised while testing this ticket:

"Download all run data via our API" in Download modal is not closed by default  [#257](https://github.com/chanzuckerberg/cryoet-data-portal/issues/257)

"Step 1 of 2" label in Configure Download dialog is missing [#258](https://github.com/chanzuckerberg/cryoet-data-portal/issues/258)

"^" button not working at click in Configure Download dialog [#259](https://github.com/chanzuckerberg/cryoet-data-portal/issues/259)

Configure download dialog is closed when clicking outside dialog [#260](https://github.com/chanzuckerberg/cryoet-data-portal/issues/260)

Even though, I am moving forward this ticket as these bugs are low priority. Thank you!
