### ISSUE TITLE
Update annotation object name styling

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#603]
The annotation object name has a title case styling applied to it, this should be removed where ever we are surfacing the field. We should be displaying the data as stored in the backend. 

This needs to be fixed in:
- [ ] Browse all data table (Browse data page)
- [ ] Runs table (Single dataset page)
- [ ] Annotation table (Single run page)

**Comment by ehoops-cz** [comment]
This looks like it's already fixed - checked the Data table, Runs table and Annotation table.
<img width="1303" alt="Screenshot 2024-07-08 at 2 43 45 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/109251328/af70519d-2c69-47bb-b23f-4efe5f5b467e">
<img width="1291" alt="Screenshot 2024-07-08 at 2 43 08 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/109251328/5e521756-1803-49ee-a07d-40e6aa3e60e4">
<img width="1329" alt="Screenshot 2024-07-08 at 2 42 59 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/109251328/2cd84b67-c8d9-4c97-bed8-d22e730cdeda">

**Comment by manasaV3** [comment]
@ehoops-cz I believe the issue is not fixed, as they still have title case styling applied, and it should be removed. 😅 

for example, the membrane should be styled in the table similarly to how it shows up on the drop down menu for object name, under metadata.

**Comment by ehoops-cz** [comment]
Oops! I was looking for all caps instead of title case.  Sorry!  I'll do this one today.
