### ISSUE TITLE
Comparing annotation object to string returns results, but should not

### ISSUE THREAD

**Issue by kandarpksk** [chanzuckerberg/cryoet-data-portal#626]
In the code written below by a participant during a usability study session, annotation objects are compared to a string, which doesn't make sense. However, many matches are found, which is a bug – I expect the comparison to error out due to a type mismatch, or at least fail. cc: @uermel

```
import cryoet_data_portal as portal
client = portal.Client()
runs = portal.Run.find(client, query_filters=[portal.Run.tomogram_voxel_spacings.annotations == "membrane"])
for r in runs:
	print(r.dataset_id)
```

**Comment by manasaV3** [comment]
We should update the copy on the download dialog box to use `sync` instead of `cp`.

**Comment by junxini** [comment]
@jgadling we forgot to point this in the meeting earlier :( Is this something you could help point async?
