### ISSUE TITLE
aws s3 cp CLI commands missing --recursive flag

### ISSUE THREAD

**Issue by JoeBeton** [chanzuckerberg/cryoet-data-portal#648]
**Describe the bug**

Suggested `aws s3 cp` CLI commands to download data fail with error message `fatal error: An error occurred (404) when calling the HeadObject operation: Key "10002/" does not exist`. 

**To Reproduce**
Steps to reproduce the behavior for entry 10002:
1. Go to webpage for entry [10002](https://cryoetdataportal.czscience.com/datasets/10002?prev=%2Fbrowse-data%2Fdatasets%3Fground_truth%3Dtrue)
2. Click on `Download dataset`
3. Copy suggested CLI command
4. Paste and run the command in the terminal
     a. command: `aws s3 --no-sign-request cp s3://cryoet-data-portal-public/10002/ 10002`
6. Get error message: `fatal error: An error occurred (404) when calling the HeadObject operation: Key "10002/" does not exist`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - aws version: aws-cli/2.15.38 Python/3.11.8 Linux/5.15.0-94-generic exe/x86_64.ubuntu.20 prompt/off

**Fix** 

I fixed this (for 10002 example) by adding the `--recursive` flag to the aws s3 command, i.e. instead of: 

`aws s3 --no-sign-request cp s3://cryoet-data-portal-public/10002/ 10002` 

 I used: 

`aws s3 --recursive --no-sign-request cp s3://cryoet-data-portal-public/10002/ 10002`

which worked as expected

**Comment by manasaV3** [comment]
Thank you @JoeBeton  for surfacing this. The command to be used for downloading datasets should be `aws s3 sync`. So, it should have been `aws s3 --no-sign-request sync s3://cryoet-data-portal-public/10002/ 10002`. The website has been updated to reflect that as well.

**Comment by manasaV3** [comment]
Once again, thank you very much, @JoeBeton  for helping us improve the portal. This issue has been addressed in production, so we will be closing out this issue.

**Comment by JoeBeton** [comment]
No problem at all, thanks for the quick fix and generally for providing the portal to the community
