### ISSUE TITLE
[In Progress] H1 Masterfile Update Work

### ISSUE THREAD

**Issue by Janeece** [chanzuckerberg/cryoet-data-portal#663]
### To-do:
- [x] #750 
- [x] #698 
- [x] #413 
- [x] #455 
- [x] #459 
- [x] #746 

### Implement as individual ticket (not blocking this ticket)
- [ ] #697 

### Completed:
- [x] #584 
- [x] #583
- [x] #458 
- [x] #454 
- [x] #416 
-

**Comment by kev-zunshiwang** [comment]
Future
- Future: Do we want to create more design templates for info panels?
- Future: do we want to circle back and create the quick start design templates?
- Future: maybe we break out education (tooltips etc) in a separate page or section
- Future maybe break out cross-page patterns? (breadcrumbs, carry over filter beahvior, responsiveness etc)

Archive files (low priority)
- Phase 2 deprioritized - need to break out implement and still deprioritized
- Prototype - may need to be ina prototypes or UXR folder

**Comment by Janeece** [comment]
Completed scope for H1 update, future corrections and refinements should be logged as request tickets or as a part of implementation support wrap up.
