### ISSUE TITLE
Support for aligned tilt-series metadata

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#68]
User Story: 
aligned tilt series with binning
- Add metadata to the tilt series to capture if the frames are aligned.
-  Include the binning factor between the unaligned and aligned tilt series here. This will typically be “1” to denote that no binning has occurred

Metadata update: 
- Add boolean field is_tilt_series_aligned. It defaults to false. 
- Add integer field tilt_series_binning_factor. It defaults to 1.

To Do: 
- Process to identify if a given tilt series is aligned.
- Process to align an unaligned tilt series

**Comment by lauramarcos** [comment]
@manasaV3 Im kinda confused as I dont think this one is for frontend QA, can you please confirm?
