### ISSUE TITLE
some data ingestion mapped data in uint8 to int8 incorrectly

### ISSUE THREAD

**Issue by anchi2c** [chanzuckerberg/cryoet-data-portal#691]
mrc definition of mode 0 was not clear until 2014 definition, and some software still used uint8 a few years after that.  We have quite some of those in jensen dataset and possibly some in others.

There is no mode defined for uint8, so we will have to shift the values.

A bad one:  https://cryoetdataportal.czscience.com/runs/11824?prev=%2Fdatasets%2F10274%3Fprev%3D%252Fbrowse-data%252Fdatasets%253Fdataset_id%253D10274

If you view its tomogram in neuroglancer, you will notice that the fiducials (the strong signal radiate a cross pattern in the top-right panel have white center.  These are supposed to be at the darkest in the image in such rendering.

**Screenshots**
![image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/35783766/7b03d273-d4cd-4ce7-84f1-f05f2f0b4d08)

A good one: https://cryoetdataportal.czscience.com/runs/11804?prev=%2Fdatasets%2F10273%3Fprev%3D%252Fbrowse-data%252Fdatasets%253Fdataset_id%253D10273
![image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/35783766/48fc9939-4198-4161-b589-21589c9d3ec7)

I compiled a list of original jensen dataset that failed my simple test of min, max values in its mrc header in its first 5 runs.  From spot checking, those passed the validation seem to be good beyond the first 5 runs, so they are likely consistent.
See https://github.com/czimaginginstitute/czii-data-portal-processing/commit/5449a64d525786001da85aa43ae5ae42bc0ce5a9

**Additional context**
ingestion issue

**Comment by junxini** [comment]
@jgadling looks like this has been in staging for a while now, has this been completed?

**Comment by jgadling** [comment]
This was addressed by https://github.com/chanzuckerberg/cryoet-data-portal-backend/pull/77
