### ISSUE TITLE
Some datasets have wrong organism names, sample_type classification.

### ISSUE THREAD

**Issue by uermel** [chanzuckerberg/cryoet-data-portal#692]
**Describe the bug**
A number of datasets have wrong `organism_name` and `sample_type`. 

**Case 1:** 
- affected datasets: `[10172, 10173, 10174, 10175, 10176, 10177, 10178, 10179, 10180, 10181, 10182, 10183, 10184, 10185, 10186, 10187, 10188]`
- old `organism_name`: `"HUVECs"`
- new `organism_name`: `"Homo sapiens"`
- new `organism_taxid`: `9606`
- new `cell_name`: `"endothelial cell of umbilical vein"`
- new `cell_type_id`: `"CL:0002618"`

**Case 2:** 
- affected datasets: `[10105, 10106, 10107, 10108]`
- old `organism_name`: `"Rat INS-1E pancreatic beta cells"`
- new `organism_name`: `"Rattus norvegicus"`
- new `organism_taxid`: `10116`
- new `cell_name`: `"type B pancreatic cell"`
- new `cell_type_id`: `"CL:0000169"`
- new `cell_strain_name`: `"INS-1E"`

**Case 3:** 
- affected datasets: `[10169, 10170, 10171]`
- old `organism_name`: `"Jurkat Human T-cell"`
- new `organism_name`: `"Homo sapiens"`
- new `organism_taxid`: `9606`
- new `cell_name`: `"T cell"`
- new `cell_type_id`: `"CL:0000169"`
- new `cell_strain_name`: `"Jurkat"`

 
**Case 4:**
- affected datasets: `[10288]`
- old `organism_name`: `"CHMP1B tubes"`
- new `organism_name`: `"Homo sapiens"`
- new `organism_taxid`: `9606`
- new `sample_type`: `"in_vitro"`
- new `dataset_publications`: `"doi:10.1091/mbc.E12-11-0785"`

**Comment by anchi2c** [comment]
https://github.com/czimaginginstitute/czii-data-portal-processing/commit/330d97379ee2fb35e7f7b8139f1c141443adf563 has the new json files that fixes this.
