### ISSUE TITLE
dataset.sample_type field values are inconsistent in case-sensitivity "cell" vs "Cell" 

### ISSUE THREAD

**Issue by anchi2c** [chanzuckerberg/cryoet-data-portal#694]
**Describe the bug**
"cell" in non-jensen data vs "Cell" in jensen data

**To Reproduce**
from cryoet_data_portal import Client, Dataset
api query
c=Client()
d1=Dataset.find(c, query_filters=[Dataset.sample_type=="Cell"])
d2 = Dataset.find(c, query_filters=[Dataset.sample_type=="cell"])
print(len(d1))
print(len(d2))

Both returns non-zero result.

**Comment by anchi2c** [comment]
https://github.com/czimaginginstitute/czii-data-portal-processing/commit/8e38d9c61ea9834973e96d8b4c854d33c39348ad fixes this in jensen data ingestion json files. Will need these new metadata ingested to fix the bug.

This is a low-priority bug. might be useful to tag on other re-ingestion tasks. @manasaV3 @jgadling

**Comment by manasaV3** [comment]
Relates to: 
https://github.com/chanzuckerberg/cryoet-data-portal/issues/693
https://github.com/chanzuckerberg/cryoet-data-portal/issues/692
