### ISSUE TITLE
Annotation counts are incorrect in the Runs page

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#729]
**Describe the bug**
The count of annotations in the Annotation table header is incorrect.

It surfaces the total number of annotations associated with the run and doesn't account for multiple shape types associated with a single annotation. So, we might see 4 records in the table, but the count would say 3 of 3 annotations. This feels inconsistent with the expected behaviour. 

**To Reproduce**
This bug can be seen on [this page](https://cryoetdataportal.czscience.com/runs/623).

**Screenshots**
<img width="1264" alt="Screenshot 2024-05-13 at 5 56 59 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/14958785/76d8d80a-2060-4aa1-964c-05cb376ddaec">

**Comment by manasaV3** [comment]
Relates to #581  #582

**Comment by manasaV3** [comment]
Blocked by: https://github.com/chanzuckerberg/cryoet-data-portal/issues/582

**Comment by junxini** [comment]
this is being addressed as part of multiple tomograms work
