### ISSUE TITLE
Masterfile update: remove title case styling from object name columns

### ISSUE THREAD

**Issue by Janeece** [chanzuckerberg/cryoet-data-portal#746]
objects names are not all title case and shouldnt be styled in that way (case should reflect the data entry)

**Comment by kev-zunshiwang** [comment]
Future
- Future: Do we want to create more design templates for info panels?
- Future: do we want to circle back and create the quick start design templates?
- Future: maybe we break out education (tooltips etc) in a separate page or section 
- Future maybe break out cross-page patterns? (breadcrumbs, carry over filter beahvior, responsiveness etc)

Archive files  (low priority)
- Phase 2 deprioritized  - need to break out implement and still deprioritized
- Prototype - may need to be ina prototypes or UXR folder
