### ISSUE TITLE
skeleton structure for browse all Depositions tab

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#773]
- new Deposition tab to be added to the browse all page
- header and footer to match existing Datasets tab

Link to designs here: https://www.figma.com/design/Rrr54QysCLa14vOnQcmejb/Janeece---Annotation-Depositions?node-id=3196-204300&t=dxTy6cmGcD7Vgzg1-0

Reminder - this should be behind a feature flag

**Comment by kne42** [comment]
note: this took a lot longer than i intended since i hooked up everything to mock data (eg. pretended our datasets were depositions). however this should save us some tech debt down the road!

**Comment by kne42** [comment]
closed by #822
