### ISSUE TITLE
new browse all Depositions tab (table)

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#775]
- Table to include the following columns:

  - key photo - this will either be author defined or fallback to the image shown in the design
  - Deposition Name
  - Deposition Date
  - Annotations
  - Annotated Objects
  - Object Shape Type

- table to be sorted by most recent deposition date first

Link to designs here: https://www.figma.com/design/Rrr54QysCLa14vOnQcmejb/Janeece---Annotation-Depositions?node-id=3196-204300&t=dxTy6cmGcD7Vgzg1-0

**Comment by kne42** [comment]
partially completed by #822; still needs to sort by deposition date
