### ISSUE TITLE
Update CryoET staging and prod RDS TLS Certificates

### ISSUE THREAD

**Issue by jgadling** [chanzuckerberg/cryoet-data-portal#777]
The TLS certificates used by our database servers are out of date. We'll need to upgrade our backend web services, and then our database to use updated certificates: https://czi.atlassian.net/wiki/spaces/SI/pages/3049259009/Infra+Eng+Upgrading+RDS+Root+CAs+rds-ca-2019

**Comment by junxini** [comment]
Certificates expire in August, this needs to be done before 8/22
