### ISSUE TITLE
Mobile friendly ML Challenge Page

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/cryoet-data-portal#818]
To make the ML Challenge Page mobile friendly, we'll need to update several of the components to be responsive

## Font Sizes

The font sizes will also need to be reduced to fit more text in the smaller viewport.

## Header

The header styling for mobile is currently broken because the nav bar doesn't hide the menu links into a more compact format such as a nav drawer or popup:

<img width="531" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/2176050/8f5cb97b-ee8d-49e7-b95a-38c893eedd42">

Scrolling right reveals that more of the header overflows:

<img width="506" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/2176050/1b56cc41-06ef-4a69-a60d-68080e943789">

## Page Content

The page content will need to be fixed to respect the max width of the viewport. Currently some of the content overflows to the right:

<img width="559" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/2176050/98fb7fd0-aa66-4b44-b4ed-60761f4f98d1">

<img width="535" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/2176050/cbfee5f1-e412-43fc-b40a-bb0059bc74b4">

<img width="596" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/2176050/f3f036dd-5d55-4028-aa81-cc2a73e1aa6f">

<img width="555" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/2176050/6a9bc2cc-2e78-4ce4-8e67-aeb9d0e65089">

<img width="567" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/2176050/f25179cb-16e0-4117-b177-eea6e09e5284">

<img width="579" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/2176050/dc2d9ffd-5a3f-48bb-b856-629c638717a7">

## Email signup form

The email signup form has a lot of overflowing text and looks broken due to its max height. We'll need to update it so that the height is dynamic:

<img width="483" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/2176050/eacfbc63-1784-44c2-b26b-6bc58ebff73f">

**Comment by junxini** [comment]
@codemonkey800 - Kevin is working on the mobile design specs this week. @kev-zunshiwang once you share it out with the team, will you also link them to this issue please?

**Comment by kev-zunshiwang** [comment]
The following is everything except the mobile banner

#1 Copy update (desktop and mobile)
- Two places need copy update, refer to [design here](https://www.figma.com/design/aL3EkC3uM17oFDmTC5h4S8/Janeece%2F-Kevin---ML-Challenge-Page?node-id=578-6306&t=oZOLujLv931bQuRw-1)

#2 Adjust padding/ margin for mobile
- refer to [design here
](https://www.figma.com/design/aL3EkC3uM17oFDmTC5h4S8/Janeece%2F-Kevin---ML-Challenge-Page?node-id=578-3637&t=oZOLujLv931bQuRw-1)

#3 Mobile top nav bar and nav menu update
- refer to [design here](https://www.figma.com/design/aL3EkC3uM17oFDmTC5h4S8/Janeece%2F-Kevin---ML-Challenge-Page?node-id=558-3352&t=oZOLujLv931bQuRw-1)
