### ISSUE TITLE
Update metadata for database schema

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#82]
Update the database schema to support the new fields:
- [x] https://github.com/chanzuckerberg/cryoet-data-portal/issues/66
- [x] #100 
- [x] #68
- [x] #69
- [x] #70
- [x] #71
- [x] #74
- [x] #102
- [x] #107
- [x] #134
- [x] #135
- [x] #139
- [x] #140
- [x] #141

Refer here for more information: 
https://docs.google.com/document/d/1zcD9OyY86gaogVZOBZPwcn0fxZ5QSFrlqXeaodJX9BI/edit#heading=h.be2fyivqz1zp

**Comment by junxini** [comment]
@manasaV3 it seems like this is treated as an Epic so i added an Epic tag. Jessica added points directly to 67,68,69 which were added to the sprint queue today. would it make sense to remove the points on the epic then?
