### ISSUE TITLE
IMAGE1- ML Challenge page - design for responsive behavior

### ISSUE THREAD

**Issue by Janeece** [chanzuckerberg/cryoet-data-portal#830]
Tasks:
- [x] P0 - Update existing mobile screen designs to reflect final designs w/ final copy
    - Goal: users on small/mobile screens can clearly read all ML challenge page copy
    - [ML challenge page mobile screens - needs update to reflect final designs/copy for H1](https://www.figma.com/design/aL3EkC3uM17oFDmTC5h4S8/Janeece---ML-Challenge-Page?node-id=313-51243&t=nkYoQRkqfXmhrYIQ-1)
- [x] P0 - Update/Recommend designs for low-lift mobile nav
    - Goal: nav doesn't look broken for users
    - Goal: get lift estimate from eng to see if mobile nav is feasible
    - [Existing mobile top nav explorations](https://www.figma.com/design/aL3EkC3uM17oFDmTC5h4S8/Janeece---ML-Challenge-Page?node-id=313-46814&t=nkYoQRkqfXmhrYIQ-1)
- [x] P1 - Update H1 implemented designs with final copy
    - can just update screen 2.4, add note about when copy was updated.
    - do not need to update other pages, but add large note that content doesn't reflect final
    - Make full frame layout use auto-layout so that dannielle can implement future copy updates herself. 
    - [H1 ML challenge page design](https://www.figma.com/design/aL3EkC3uM17oFDmTC5h4S8/Janeece---ML-Challenge-Page?node-id=296-6620&t=nkYoQRkqfXmhrYIQ-1)
    - [Final copy for ML Challenge page](https://docs.google.com/document/d/1Aaxslc-2HuxUFouHKwZlKWfFKr2kkfEcRr7SgBcMmVU/edit?usp=sharing)

OOS:
- mobile "jump to nav" (is in the design file, but will not touch for implementation, remove from mobile screens)

**Comment by kev-zunshiwang** [comment]
We handed off the spec before the copy was finalized.

**Comment by kev-zunshiwang** [comment]
- H1 launch
- Mobile responsiveness is a launch
- post launch

**Comment by kev-zunshiwang** [comment]
This one is finished - P1 - Update H1 implemented designs with final copy

**Comment by Janeece** [comment]
@kev-zunshiwang heads up that Jun and I upped the mobile nav to a P0 -- i dont think this affects you though!
