### ISSUE TITLE
Remove Citations field from metadata panel

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#831]
**Describe the bug**
In the metadata panel, there's a field titled "Citations". This field is empty and should be removed in the UI and also in the backend

Locations in the UI: 
1. single dataset page metadata panel
2. single run page metadata panel

**To Reproduce**
1. Go to https://cryoetdataportal.czscience.com/datasets/10083?metadata=dataset&tab=metadata
2. Click on "view all info"

**Screenshots**
<img width="1712" alt="Screenshot 2024-07-02 at 10 41 48 AM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/98626158/64c46374-8d2c-4b9e-935d-1015572d8c3c">

**Comment by bchu1** [comment]
No longer displayed/queried in the FE. Not sure if removing from Python client/GQL schema is a priority since that seems like it would be a breaking change, so leaving the bug as is.

**Comment by junxini** [comment]
Manasa from sprint planning: in the BE list for deprecation, @manasaV3 to create ticket for BE. closing this FE ticket
