### ISSUE TITLE
Series is Aligned Metadata doesn't have an API field

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#852]
Runs on the data portal have a "Series is Aligned" field in their Tilt Series metadata which does not have a corresponding API field.

<img width="467" alt="Screenshot 2024-07-09 at 3 24 38 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/92180364/e4b235ad-194a-402b-ab37-67e37203c6ed">

**Comment by manasaV3** [comment]
I believe this has been addressed https://github.com/chanzuckerberg/cryoet-data-portal/blob/8c0d9d814234608b60afc60c09a123678b6aeccc/client/python/cryoet_data_portal/src/cryoet_data_portal/_models.py#L1279.
