### ISSUE TITLE
Update configs with deposition metadata

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#876]
The configuration schema requires valid metadata for deposition.

The fields to be updated are:
1. deposition.authors (currently mapped to dataset's author, to be overriden wherever necessary) 
2. deposition.cross_references
3. deposition.dates (currently mapped to dataset's dates, to be overriden wherever necessary)
4. deposition.deposition_description
5. deposition.deposition_identifier (already assigned)
6. deposition.deposition_title
7. deposition.deposition_types (pre-filled based on the available entities)
8. deposition_keyphotos (optional)

**Comment by manasaV3** [comment]
For tackling grant jensen data, can we add another entry in the dictionary that of the [metadata](https://github.com/czimaginginstitute/czii-data-portal-processing/blob/main/src/data_portal_processing/jensendb/portal_dataset_grouping.json) that maps group ids to deposition metadata?

**Comment by anchi2c** [comment]
Sure.  I will need to know the "already-assigned deposition identifier", item 7.  I won't put in deposition dates and might not know the cross-references. @manasaV3

**Comment by manasaV3** [comment]
@anchi2c The [Jensen config generation script](https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/b304fc9fafa5797f1506476b2f9ae7664e2e39d9/ingestion_tools/scripts/gjensen_config.py#L360) will take the grouping from the [metadata file](https://github.com/czimaginginstitute/czii-data-portal-processing/blob/main/src/data_portal_processing/jensendb/portal_dataset_grouping.json) and create the deposition identifier. 

So, if you can create the deposition metadata mapping to the value for `dataset_group`, and we can update the script to use the same. :)
