### ISSUE TITLE
Improve error message when downloading to a new folder location

### ISSUE THREAD

**Issue by kandarpksk** [chanzuckerberg/cryoet-data-portal#887]
When dest_path in any of the download methods in the API is a new folder location, i.e. a folder that doesn't currently exist, the error message shown is confusing: “Recursive downloads require a base directory”

**Comment by Bento007** [comment]
How do we feel about creating the base path if it doesn't already exist. That makes one less step for our users to take, or if we don't want to assume what the users want, we can add a flag to make auto creating the directory optional.

**Comment by Bento007** [comment]
> How do we feel about creating the base path if it doesn't already exist. That makes one less step for our users to take, or if we don't want to assume what the users want, we can add a flag to make auto creating the directory optional.

I see that we do [create the dest_path](https://github.com/chanzuckerberg/cryoet-data-portal/blob/3cf96cb6b785b1d8e72baef57f42b7b6706bca69/client/python/cryoet_data_portal/src/cryoet_data_portal/_file_tools.py#L90-L90) if `recursive_from_prefix` is False. What was the reasoning behind this?

**Comment by manasaV3** [comment]
> I see that we do [create the dest_path](https://github.com/chanzuckerberg/cryoet-data-portal/blob/3cf96cb6b785b1d8e72baef57f42b7b6706bca69/client/python/cryoet_data_portal/src/cryoet_data_portal/_file_tools.py#L90-L90) if recursive_from_prefix is False. What was the reasoning behind this?

I believe this is because, if it is not a recursive download we are downloading a complete directory or else it is pulling down a single file which should be easier to identify.  So, creating the directory helps consolidate all of the contents what we are downloading for a recursive download.

**Comment by kandarpksk** [comment]
My original understanding was that the error is thrown whenever the destination path doesn't exist. But from Manasa's comment, it seems like that's not always true. I think we should just make it consistent and create the missing folder in the path.

**Comment by manasaV3** [comment]
@kandarpksk to confirm, we won't be creating a directory in all the cases when the user doesn't provide a destination path. (ie) we will only create a directory for the cases where we are downloading a directory, like in the case of a zarr file or if we are downloading an entire run. 
If the user explicitly provides a destination path that is not a directory, I think we shouldn't be creating that directory, but should provide a user understandable error that explains the path they provided is not a directory, so we can't download files into that path. Let me know what you think.

**Comment by kandarpksk** [comment]
Makes sense. I certainly don't think we should always create a directory.
