### ISSUE TITLE
Links to "section" headers don't scroll to the right position

### ISSUE THREAD

**Issue by kandarpksk** [chanzuckerberg/cryoet-data-portal#888]
Clicking on links to "sections" scrolls to the section in such a way that the section header is not visible (it's probably hidden by the header). Example links:
- [Dataset Overview Page](https://chanzuckerberg.github.io/cryoet-data-portal/cryoet_data_portal_docsite_data.html#dataset-overview-page)
- [Documentation for s3_metadata_path](https://chanzuckerberg.github.io/cryoet-data-portal/python-api.html#cryoet_data_portal.Annotation.s3_metadata_path)

Maybe something to keep in mind is if this may be automatically fixed when switching to the sphinx-immaterial theme (#889)?

**Comment by junxini** [comment]
hey @dgmccart i assigned you to this bug, not sure if it's needed after we switch to the new theme. please close out if the theme switch fixes this bug, or feel free to reassign to Melissa if you think she can help

**Comment by dgmccart** [comment]
Thanks for the tag! This item is on the list for Melissa's work. We'll see if just changing the theme fixes things, but if not, Melissa can help come up with a solution.
