### ISSUE TITLE
Update python API client to support new models

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#900]
Update python client to reflect the new data model.  As there is a large change in the schema, a new major version needs to be released that might not be completely backward compatible. 

It should also support the following functionalities: 

- [ ] Support the new data model relationships
- [ ] Point to the new api endpoint
- [ ] Adds new transformation utility for transforming annotations from one predefined spec to another
- [ ] Supports command line interface functionality

**Comment by andy-sweet** [comment]
Assuming we can automatic define the Python client from the schema (see https://github.com/chanzuckerberg/cryoet-data-portal/issues/900), then there might be limited work here.

**Comment by manasaV3** [comment]
Closing this as the related work is captured in https://github.com/chanzuckerberg/cryoet-data-portal/issues/937
