### ISSUE TITLE
Automate publish of python client to pypi

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#902]
Currently, there is a manual step in the release of the python api client package to pypi once a build is available. To simplify this and completely automate the workflow, we can publish the distribution to pypi as a part of the [github workflow](https://github.com/chanzuckerberg/cryoet-data-portal/blob/main/.github/workflows/py-build.yml).

Example action that could be used for publishing the package: https://github.com/marketplace/actions/pypi-publish

**Comment by Bento007** [comment]
@manasaV3 how is the release version change determined?

**Comment by Bento007** [comment]
@jgadling I see the release process has this step
https://github.com/chanzuckerberg/cryoet-data-portal/blob/df26183b643c59b74d1273050e9efcbe36b57d16/client/python/cryoet_data_portal/release_process.md#L59-L59
What does perform end-user testing mean?

**Comment by manasaV3** [comment]
> how is the release version change determined?
If there is a breaking change, we update the major version. If there is a feature addition we should update minor version, and if a release only has fixes and chores we should bump up the patch version.

**Comment by Bento007** [comment]
Blocked on access to testpypi

**Comment by manasaV3** [comment]
Closing this, as https://github.com/chanzuckerberg/cryoet-data-portal/issues/1072 better captures the blocker.
