### ISSUE TITLE
IMAGE1 - Design updates to Data Schema

### ISSUE THREAD

**Issue by Janeece** [chanzuckerberg/cryoet-data-portal#906]
### Roles: 
- Project lead: Dannielle - will define changes needed
- Designer: Yun (brand/comms)
-  Design consult: Janeece
- Informed: Jun, Manasa (?), Utz/anchi

### Background:
- Portal's documentation site needs an updated and easy to understand diagram to explain the current data schema. We think that design's phase 2 data schema is a good start and could be modified/updated to fit the needs. 
- [Phase 2 Data Schema figjam](https://www.figma.com/board/ja7fThsAYL6u4I38HxefW5/CryoET-Data-Portal-%7C-Data-Schema?node-id=0-1&t=TTRam1hHK1hhSPAE-1) (create new version)

### Design tasks:
- create updated version of data schema for use on documentation site, following Dannielle's direction

**Comment by dgmccart** [comment]
The new data schema is now [live on the site](https://chanzuckerberg.github.io/cryoet-data-portal/cryoet_data_portal_docsite_data.html)!
