### ISSUE TITLE
Support Bitmap annotations for tomograms

### ISSUE THREAD

**Issue by jgadling** [chanzuckerberg/cryoet-data-portal#91]
We want to support bitmap (MRC and zarr) annotations for tomograms. We need to add support for this to our metadata spec (include an annotation type & path to the zarr/mrc files) as well as add it to our metadata schema. Additionally, we need to import bitmap annotations for any dataset that we ingested before we supported this feature.

**Comment by junxini** [comment]
@jgadling i updated the status from backlog to in progress, please revise if that's not accurate
