### ISSUE TITLE
Browse all deposition tab

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#915]
- Add a new tab on the Browse All Data page titled "Depositions #". the # represents the total count
- when clicking on the tab, user will see the table (covered in #775)

Link to designs: https://www.figma.com/design/Rrr54QysCLa14vOnQcmejb/Janeece---Annotation-Depositions?node-id=3225-61203&t=Zi9SnSdlPV77a93N-0

**Comment by kne42** [comment]
closed by #822
