### ISSUE TITLE
Table and pagination - single deposition page

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#922]
- Deposition table to include the following columns:
  - dataset key photo
  - dataset name
  - organism
  - run
     - subtext "With deposition data" 
  - annotations
     - subtext "Deposition only"
  - annotated objects
     -  subtext "Deposition only" 

- Enable pagination similar to other pages
- Clicking on a row will bring user to the dataset with "deposition state" applied (refer to #925) 

Link to designs: https://www.figma.com/design/Rrr54QysCLa14vOnQcmejb/Janeece---Annotation-Depositions?node-id=3285-83985&t=Zi9SnSdlPV77a93N-0

**Comment by kne42** [comment]
> Clicking on a row will bring user to the dataset with "deposition state"

note: not included in pointing since it is already captured in #925
