### ISSUE TITLE
Identify framework for validation

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#932]

**Comment by daniel-ji** [comment]
See draft here ("AWS S3 Data Validation Proposal"): https://docs.google.com/document/d/1bBCOuwCiAyv8a5XXQrxbxXfggOnHfMwn7nnZEOQ3M_c/edit?pli=1#heading=h.romg1qou01zy

**Comment by daniel-ji** [comment]
As of now, we decided to go with Allure + Pytest. Will re-open if decision changes / discussion arises again.
