### ISSUE TITLE
Python API documentation not in alphabetical order

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cryoet-data-portal#944]
**Describe the bug**
The python api doc site does not display variables in alphabetical order.

**To Reproduce**

go to https://chanzuckerberg.github.io/cryoet-data-portal/python-api.html

**Screenshots**
![Screenshot 2024-07-25 at 1 49 37 PM](https://github.com/user-attachments/assets/03674142-66c2-4147-a387-ce05c6652893)

**Branch**
 - https://github.com/chanzuckerberg/cryoet-data-portal/commit/659bea3fb316b88927b4f215a9e5b9286f5e0bb9

**Comment by junxini** [comment]
tagging @dgmccart as part of doc site build work. is this something you could work with Melissa on?

**Comment by dgmccart** [comment]
Yes, absolutely. I will tag her here and discuss in our next 1:1.
