### ISSUE TITLE
Add support for ingesting mesh annotations

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#951]
# Need

We need to support ingesting mesh as new annotation type in the data ingestion process.

### Out of scope for this ticket: 
Adding mesh annotation visualization to neuroglancer.

### Importing mesh annotation
This requires being able to pull mesh files from a source destination, with formats of (`*.hff`, `*.stl`, `*.obj`, `*.vtk`) and convert them into the portal standard format `glb`.  Find more on glb format [here](https://www.modelo.io/damf/article/2024/04/26/1219/understanding-the-glb-file-format?hl=en).

Related code: https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/2147fc30d8fdf0e2ed0a223899a003d1883927cd/ingestion_tools/scripts/importers/annotation.py#L158

Recommended library for working with meshes:  [trimesh](https://trimesh.org/)

#### Mesh import related validations:
- Ensure they are in pixel scale of the parent tomogram, to be consistent with the point annotations

#### Mesh import related configurations:
- to be added

#### Generating object count
The object count can be defaulted to 1

# Definition of Done
- Add source mesh to yml format.
- update ingest config to support mesh annotations
- The mesh should align perfectly with a tomoagram. I'll need to ask Anchi how to do this or if it correct
- update the [documentation](https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/main/ingestion_tools/dataset_configs/template.yaml#L37) to include the new mesh data format for the yml file
- update the [validation schema](https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/main/schema/v1.1.0/dataset_config.yaml). contact daniel if help is needed.

# Validation
- compare how hff looks using scikit rendered vs gbl
  - Examples:
    - s3://cryoetportal-rawdatasets-dev/Grotjahn/Membrane_surface_mesh/
    - s3://cryoetportal-rawdatasets-dev/mahrukh_usmani_06_2024/Data_Set_1/tomo_0001/
  - [modify](https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/main/ingestion_tools/dataset_configs/10000.yaml#L411) and run [standardize_dirs.py](https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/main/ingestion_tools/docs/standardize_dirs.md)
  - for mesh validation https://scikit-image.org/docs/stable/auto_examples/edges/plot_marching_cubes.html

**Comment by Bento007** [comment]
@manasaV3 do we have example (*.hff, *.stl, *.obj, *.vtk) data?

**Comment by manasaV3** [comment]
Related resource can be found [here](https://docs.google.com/document/d/1oKfZlptIZSRL8dLlLLzkqAgMycWOWE_j3_lXfvCcV-s/edit#heading=h.51lcymk3f6c3).

**Comment by manasaV3** [comment]
```
- Mesh:
      file_format: str # enum [hff, stl, obj, vtk, glb]
      glob_string: str  # [path to file]
      glob_strings: list[str] # [paths to file]
      is_visualization_default: true # bool 
```
@uermel  Should we need any other configuration values for the mesh?

**Comment by Bento007** [comment]
For the `*.hff` format we can use the [sfftk](https://sfftk.readthedocs.io/en/latest/toolkit.html#data-model) python library to convert to `*.stl` file.

## [sfftk](https://sfftk.readthedocs.io/en/latest/toolkit.html#data-model)
[License](https://sfftk.readthedocs.io/en/latest/toolkit.html#id5): Apache License, Version 2.0.  
https://github.com/emdb-empiar/sfftk/tree/master

This is a small specialized library for handling hff and sff formatted data. Is receives updates a few times a year. However the [data model ](https://emdb-empiar.github.io/EMDB-SFF/) used for the `hff` format is constantly evolving. The owner of the the python library and the data model are the same organization. This means it's more likely the library will maintain compatibility with the data model.

**Comment by Bento007** [comment]
@manasaV3 The hff format stores multiple meshes in the same file, do we want to store each mesh in it's own glb file or as one mesh?

**Comment by manasaV3** [comment]
> The hff format stores multiple meshes in the same file, do we want to store each mesh in it's own glb file or as one mesh?

That might depend. If all of the meshes are a part of the same annotation object, we should keep it as a single mesh. For example, in the case of a membrane meshes there could be multiple meshes but it should be a single file. 
But, if a mesh contains multiple different annotation objects in the same source hff file, they should be saved as separate glb files. 

I am not sure if we have any use cases at the moment of the second type. If we do, we can tackle that as a separate issue. @uermel

**Comment by uermel** [comment]
> ```
> - Mesh:
>       file_format: str # enum [hff, stl, obj, vtk, glb]
>       glob_string: str  # [path to file]
>       glob_strings: list[str] # [paths to file]
>       is_visualization_default: true # bool 
> ```
> 
> @uermel Should we need any other configuration values for the mesh?

@manasaV3  We likely need a scale factor in case the mesh has a different voxel size than the one we're targeting (similar to the `binning` value for points)

> The hff format stores multiple meshes in the same file, do we want to store each mesh in it's own glb file or as one mesh?

Agree with what @manasaV3 said, if the meshes relate to different annotated objects they should be stored seperately. If not, they can go into the same file.

**Comment by Bento007** [comment]
> @manasaV3 We likely need a scale factor in case the mesh has a different voxel size than the one we're targeting (similar to the binning value for points)

Some mesh formats such as hff include the scale factor in the metadata. I don't know if this is true for all formats. So for hff we can make it optional to include and extract it from the format.

> Agree with what @manasaV3 said, if the meshes relate to different annotated objects they should be stored seperately. If not, they can go into the same file.

Which meshes to combine and separate will need to be specified in the ingestion-config, and a unique files name will need to be provided for each.
